### ISSUE TITLE
Speed test in Linux terminal

### ISSUE THREAD

**Issue by marrobHD** [librespeed/speedtest#235]
## Description
Speed test in Linux terminal like speedtest-cli

## Why it should be implemented
so that the speed test also works in a Linux terminal without a desktop.

## Optional: implementation suggestions
If you have experience in this field, feel free to give us suggestions

## Optional: screenshots
Add some screenshots, mockups, ... if they help clarify what you want

**Comment by dunklesToast** [comment]
Will develop this later this week.

**Comment by marrobHD** [comment]
Cool. Can you than post it here?

**Comment by adolfintel** [comment]
Planned after iOS template is done

**Comment by purpl3F0x** [comment]
I was about to ask for this. 👍

**Comment by adolfintel** [comment]
I was initially against the idea, because it would be worse than iperf, but a lot of people want it, so I guess I'll be doing it
