### ISSUE TITLE
Support for UDP

### ISSUE THREAD

**Issue by robertheadley** [librespeed/speedtest#240]
## Description
Add support for testing over the UDP protocol.	

## Why it should be implemented
Fiber connections provide a more accurate result over UDP than TCP

## Optional: implementation suggestions
I work for an internet service provider. We currently use Speedtest Custom by Ookla and it works for most of our customers. However if a Fiber customer uses it, it shows less than impressive results.

**Comment by adolfintel** [comment]
That would be nice, unfortunately you can't use UDP over HTTP.

**Comment by Strykar** [comment]
> That would be nice, unfortunately you can't use UDP over HTTP.

@adolfintel You can now with HTTP2/QUIC - https://kinsta.com/blog/http3/
