### ISSUE TITLE
results/stats.php don't work with postgresql

### ISSUE THREAD

**Issue by jacekjaros** [librespeed/speedtest#242]
## Description
result panel is unable to display latest results

## Server
hitch+varnish+apache2
php - 7.3.9-1~deb10u1
postgresql11

## Client
linux, firefox

## Steps to reproduce
open url, run test, check result page

## Expected behaviour
i should see latest tests list

list are not displayed because postgresql don't support params in #,# format
```
ERROR:  42601: LIMIT #,# syntax is not supported
LINE 1: ...xtra from speedtest_users order by timestamp desc limit 0,10...
```

**Comment by adolfintel** [comment]
I didn't know they changed the syntax.
Does it work if you replace it with `limit 100` [at line 113](https://github.com/librespeed/speedtest/blob/1b059e6cc61b57bda549c4ffcaf57b4526a1f0d6/results/stats.php#L113)?

**Comment by adolfintel** [comment]
Fixed
