### ISSUE TITLE
couldn't start speedtest

### ISSUE THREAD

**Issue by tufand** [librespeed/speedtest#244]
## Description
A short description of what's going on
couldn't start speedtest
## Server
Every info you can provide about your server: web server, database, PHP version, ... as well as server-side speedtest settings
If possible, provide an URL to your speedtest so we can check it

## Client
Browser, OS, type of connection, unusual software, ...

## Steps to reproduce
* Do this
* Do that
* Bad stuff happens

## Expected behaviour
What should have happened

## Screenshots
If necessary, add screenshots of the test. 
F12 > Network screenshots can be particularly useful
![resim](https://user-images.githubusercontent.com/31701244/66256891-85aa7a00-e79b-11e9-8eff-158d0e9d2ad2.png)

**Comment by adolfintel** [comment]
Issues are not for troubleshooting.

Also, I cannot help you without any information, and you're using an old version of the speedtest. Simply redownloading it will probably fix your problem.

If you need help, write me at info@fdossena.com
