### ISSUE TITLE
Upload speed doesn't reach its possible maximum value.

### ISSUE THREAD

**Issue by mnihyc** [librespeed/speedtest#245]
It seems that it's multi-thread when testing Download speed, but single-thread when testing Upload speed.
The network provider usually limits the network bandwidth for one single request (at least in my region) and it has to be multi-thread to reach the possible maximum value of network bandwidth.

**Comment by adolfintel** [comment]
The number of streams used in the upload test varies with the browser at the moment, but I think I'll set it to 3 in the next version since it seems to be the best value
