### ISSUE TITLE
GPS of the test

### ISSUE THREAD

**Issue by jasonwinget** [librespeed/speedtest#246]
## Description
Store the location of a mobile device as a configurable option.

## Why it should be implemented
Speed tests for mobile devices plotted on a map from the telemetry data, to show where data is better or worse by geography.

## Optional: implementation suggestions
Include with telemetry upload.  Cross-reference with carrier info returned with GetIP.

**Comment by jasonwinget** [comment]
Do not use the geo-IP location information though, use the sensor on the mobile device if it is available, fall back to GeoIP.

**Comment by adolfintel** [comment]
This is a duplicate of #223 .
As I said, I don't want to implement this for privacy reasons, but the guy forked the project and added it himself so you can use his code, just update the rest of the files.
