### ISSUE TITLE
CLI long-term analysis

### ISSUE THREAD

**Issue by meifi** [librespeed/speedtest#248]
Thanks for sharing this great project! 

## Description
it is posible to generate two new files, which can be called seperated? 
one file starts the full speedtest ad hoc an give the response as json
the other file only gives the ping and jitter times as json response. 

## Why it should be implemented
With this feature, you can start long-term analysis with influxdb and grafana or rrd

**Comment by adolfintel** [comment]
I'll keep this in mind when I'll develop the CLI client
