### ISSUE TITLE
nginx always print stderr

### ISSUE THREAD

**Issue by lizhaode** [librespeed/speedtest#250]
## Description
I use php-fpm7.2 and nginx

## Server
my computer

## Client
chrome

## Steps to reproduce
the nginx log write:
```log
[error] 2586#2586: *4368 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: localhost, server: localhost, request: "GET /backend/getIP.php?isp=true&distance=km&r=0.06643249990611233 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:",.........
```
and I set php user and group is nginx. Set backend folder is  nginx:nginx, it also print this error

## Expected behaviour
What should have happened

## Screenshots
If necessary, add screenshots of the test. 
F12 > Network screenshots can be particularly useful

**Comment by dunklesToast** [comment]
> Server - my Computer

Doesn’t help much. I guess it’s Linux.
Could you please post your nginx.conf here?

**Comment by adolfintel** [comment]
Yeah, we need more info to be able to help you.
I'll close the issue but feel free to post more details.

**Comment by lizhaode** [comment]
nginx config:
```
location ~ \.php$ {
        root           html;
        fastcgi_pass   unix:/run/php/php7.2-fpm.sock;
        fastcgi_index  index.php;
    #    fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
    #    fastcgi_param DOCUMENT_ROOT		$realpath_root;
        fastcgi_param SCRIPT_FILENAME	$document_root$fastcgi_script_name;
        include        fastcgi_params;
    }
```

php config:

```
user = nginx
group = nginx

listen.owner = nginx
listen.group = nginx
```

backend folder properties

```
drwxr-xr-x 2 nginx nginx 4.0K Oct 29 12:45 backend/
```

**Comment by dunklesToast** [comment]
Config it Self looks good. Could you move `include fastcgi_params;` on top of the location directive and reload your nginx and see, if the error persists?

**Comment by lizhaode** [comment]
> Config it Self looks good. Could you move `include fastcgi_params;` on top of the location directive and reload your nginx and see, if the error persists?

I did as you say. The error log is the same as before. Mybe `fastcgi_param SCRIPT_FILENAME	$document_root$fastcgi_script_name;` config not effect?
