### ISSUE TITLE
Free Docker Image host

### ISSUE THREAD

**Issue by eliashuber02** [librespeed/speedtest#255]
## Description
I could host a Docker Image on my Server.

## Why it should be implemented
Because it helps everyone!

## Optional: implementation suggestions
You can find a registry web interface at [registry.huber.host](http://registry.huber.host), I've made it publicly accessible now!

**Comment by adolfintel** [comment]
Can't we already download a docker image from docker hub? How would this be any better?

**Comment by eliashuber02** [comment]
I only found a not up-to-date version, that's why I got the idea.

**Comment by adolfintel** [comment]
I see a build from 2 days ago, do you see an older version?

Anyway, if you provide hosting services and you want to help the project, the best way would be to host a demo test point, we currently have only 4 ;)

**Comment by eliashuber02** [comment]
Oh, okay could you send me a link to it?

And yes I've already build it and set it up under: speedtest.srv1.huber.host

Location is Germany, Nuremberg
Hosting Provider is: Contabo

**Comment by adolfintel** [comment]
The demo is at https://speedtest.fdossena.com

How much bandwidth do you have? Both in terms of speed and traffic

**Comment by eliashuber02** [comment]
speedtest.srv1.huber.host => 200Mbit/s
speedtest.srv2.huber.host => 100 Mbit/s

And I'll soon get another one with 400Mbit/s - not available yet

**Comment by eliashuber02** [comment]
I just found out that my Nginx Reverse Proxy limits the maximum bandwidth a little bit, but that shouldn't be a problem, am I right?

**Comment by adolfintel** [comment]
What's the maximum speed?

**Comment by adolfintel** [comment]
That's not much for a speedtest unfortunately, ideal would be at least 1gbps

**Comment by eliashuber02** [comment]
Okay, anyways, if I get 1gbps I'll write you again!
