### ISSUE TITLE
Add captcha support

### ISSUE THREAD

**Issue by Strykar** [librespeed/speedtest#257]
## Description
Add Google captcha to reduce spam requests 

## Why it should be implemented
It would trim traffic usage to legitimate users and keep bandwidth costs down.

**Comment by adolfintel** [comment]
The next update of librespeed (next few months) will be focused on security and abuse prevention. In particular, I'm thinking of a token based system to allow for rate limiting on a server basis, as well as less abusable telemetry.
Adding recaptcha is out of the question though, I'm not infecting the project with google malware; besides, it would be extremely annoying for the users.

**Comment by Strykar** [comment]
@adolfintel What method of rate limiting did you have in mind and how are you certain it won't be circumvented?

**Comment by adolfintel** [comment]
Each server will have a per-IP rate limit (like 5 tests per IP per hour). This will be enforced by each test point. When the client wants to run the tests, it asks for a token, which is valid for 1 minute (or 1 test, I have yet to decide how to implement it), and this has to be presented to the server every time a connection to one of the PHP files is made.
Too many tests and you get no token.



On November 26, 2019 7:36:32 PM GMT+01:00, "Avinash H. Duduskar" <notifications@github.com> wrote:
>@adolfintel What method of rate limiting did you have in mind and how
>are you certain it won't be circumvented?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/librespeed/speedtest/issues/257#issuecomment-558762839

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
