### ISSUE TITLE
Free Public Available SpeedTest Sites

### ISSUE THREAD

**Issue by MrCoding** [librespeed/speedtest#261]
Dear All,

Some of my users asked me if it is possible to provide the SpeedTest served from some of my hosting locations. And so I created the link [ http://SpeedTest.TomDings.com/ ] which makes it possible to start the SpeedTest from the standard locations [ Italy and Finland] and some of my own from France, Paris and Germany, Munchen.

A few more will be added very soon. Hopefully you like the idea. Would you like to add your own location(s) ? Please let me know. Maybe even better to add some additional code to make it possible to add your own test locations automatically. Working on it!

Enjoy your day!

Tom

**Comment by dunklesToast** [comment]
The URL does not resolve.

**Comment by adolfintel** [comment]
I appreciate your idea, but please don't use the demo servers, they can't handle much traffic and they're already handling over 100k tests per week.

If you want to have your server(s) added to the demo, contact me at info@fdossena.com so I can test them and add them.

**Comment by MrCoding** [comment]
Okay. Will remove the Demo Servers. Name is resolving but changed some Dns records. It is done by CloudFlare. Probably it is available in a few minutes.

**Comment by MrCoding** [comment]
All tests done will be stored on a server so people are able to compare tests from each other. There will be an option to be able to turn on/off the public sharing of your statistics. Just in case! Will let you know when it is working. Adding the features right now!

**Comment by MrCoding** [comment]
Just for the moment till I am done changing the source code :

Link : https://speedtest.tomdings.com/

**Comment by dunklesToast** [comment]
That’s the same link and it’s still not resolving. Even not on CloudFlares Servers

**Comment by MrCoding** [comment]
root@vps1de:/var/www/speedtest.tomdings.com/web# nslookup speedtest.tomdings.com
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	speedtest.tomdings.com
Address: 104.27.173.171
Name:	speedtest.tomdings.com
Address: 104.27.172.171

**Comment by MrCoding** [comment]
![image](https://user-images.githubusercontent.com/680842/71030380-0a950680-20f0-11ea-9c0c-a995bd040400.png)

**Comment by MrCoding** [comment]
Just registered a completely new domain name : myInternetSpeed.Xyz

Takes a little bit of time before it is public available.
