### ISSUE TITLE
Do not make third party request to all speedtest servers to preserve privacy

### ISSUE THREAD

**Issue by Perflyst** [librespeed/speedtest#264]
## Description
Currently the speedtest site connects to all other configured servers. Also with a lot of servers this can take a lot of time.
This is not ideal in terms of privacy. The servers should only be contacted if a speedtest is really made.

## Why it should be implemented
Any user would have better privacy.

**Comment by adolfintel** [comment]
There is no other way to determine which server has the lowest ping.
Do you have a better solution?
