### ISSUE TITLE
Latency and Jitter really high

### ISSUE THREAD

**Issue by pteratech** [librespeed/speedtest#265]
We have customers complaining their latency and jitter is way too high. I ran ping plotter to one of our customers and over the hour it showed avg ping 13.5 Min 3.0 Jttr at 10.2
The speed test says Ping 25.15 Jttr 25.59
Next test said 28.44 jttr 53.45

A very big difference - any suggestions?
Thanks

Others report 
ping 168 jttr 82
ping 30 jttr 251
ping 39 jttr 126

**Comment by adolfintel** [comment]
It's hard to tell what the problem is without more information.
Anyway, write me at info@fdossena.com for troubleshooting, issues are for bugs and feature requests.

**Comment by jimidak** [comment]
I see the same issue. Was there any resolution to this?
