### ISSUE TITLE
Docker doesn't seem to work anymore. 404 from apache

### ISSUE THREAD

**Issue by RyanEwen** [librespeed/speedtest#266]
Docker doesn't seem to work anymore. 404 from apache since pulling the latest image.

**Comment by IronicBadger** [comment]
Worked OK just now for me :+1:

**Comment by adolfintel** [comment]
Works for me as well. Try deleting the docker image and redownload it.

**Comment by RyanEwen** [comment]
Had this on 3 separate Ubuntu 18.04 VMs. One wasn't updated and sure enough when I pulled the latest I saw the issue. Went back to the previous image and they're all fine again.

**Comment by IronicBadger** [comment]
Post the output of `docker images` for the speedtest image to verify the SHA you have locally.

**Comment by adolfintel** [comment]
I triggered a rebuild on docker hub. Try fetching the image now.

**Comment by RyanEwen** [comment]
@IronicBadger  it was `adolfintel/speedtest   latest              bf6464f94f3a        5 weeks ago         435MB`

Since @adolfintel's rebuild, it is `adolfintel/speedtest   latest              e8008eca3420        57 minutes ago      435MB`

I just realized that I access this through nginx.. that seems like it might have something to do with it..

More details:

`Docker version 19.03.5, build 633a0ea838`
`docker-compose version 1.22.0, build f46880fe`

`docker-compose.yml:`
```
  speedtest:
    image: adolfintel/speedtest:latest
#    image: speedtest_old
    ports:
      - 8080:80
    restart: always
```

nginx conf:
```
server {
    listen 80;

    server_name <removed>

    root /config/www/;
    index index.html index.htm index.php;

    location / {
        root /www;
        autoindex on;
    }

    client_max_body_size 32M;

    location /speedtest {
        proxy_pass              http://127.0.0.1:8080;
        proxy_set_header        X-Real-IP               $remote_addr;
        proxy_set_header        Host                    $host;
        proxy_set_header        Scheme                  $scheme;
        proxy_set_header        X-Forwarded-For         $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto       $scheme;
        proxy_set_header        X-Forwarded-Host        $host;
        proxy_redirect          off;
    }
```

**Comment by RyanEwen** [comment]
Seems not to be nginx - same result when going directly to the port that I map the container to, eg http://my-site.com:8080/speedtest/

**Comment by RyanEwen** [comment]
Okay got it working by changing
```
    location /speedtest {
        proxy_pass              http://127.0.0.1:8080;
```

to

```
    location /speedtest {
        proxy_pass              http://127.0.0.1:8080/;
```

Not sure why I have to do that now.. but I'm glad it's working

**Comment by adolfintel** [comment]
@fazo96 Do you know why this is happening?

**Comment by IronicBadger** [comment]
You wouldn't go to `/speedtest` unless you were going through nginx.

**Comment by RyanEwen** [comment]
The old nginx rule without the trailing slash worked with the older speedtest. 

Maybe the apache image changed underneath yours somewhere along the line and now it's not listening for requests the same way it used to. 

Good news is that it only affects reverse proxying and the container is fine standalone.
