### ISSUE TITLE
Skipping some tests by setting their url to null

### ISSUE THREAD

**Issue by beppe9000** [librespeed/speedtest#268]
I see the code throws exceptions if any test endpoint is not valid. What I suggest is to treat the explicit `null` as a "skip test" condition. Here is an example download-only server definition.
```JSON
{
  "name":"Test #342 (Download Only)",
  "server":"http://cors.jejaju.com/",
  "dlURL":"Snickerdoodles.pdf",
  "ulURL":null,
  "pingURL":null,
  "getIpURL":null
}
```
Also for this specific case I think a shorthand function like 
```javascript
blah.testDownload("http://cors.jejaju.com/Snickerdoodles.pdf");
```
could be useful to quickly return a speed test object ready to be started. This also applies to the other types of test.

**Comment by adolfintel** [comment]
Behavior when some URLs are set to null was never defined so I can understand why it's failing.

That said, the proper way to disable some tests would be to set the test order (in your case) to just "D".

I will keep this in mind for the next update though.
