### ISSUE TITLE
QUESTION: standalone = frontend + backend, but where is backend?

### ISSUE THREAD

**Issue by bizlevel** [librespeed/speedtest#269]
Hello.
I see that we can run in standalone mode or in frontend mode.
But if we run in frontend mode, where is backend?
How to configure docker-compose run in separate part front + back ?
Thanks.

**Comment by adolfintel** [comment]
There are 3 modes for the docker image:
* Standalone is for single server installations, this is the default and the one that most people will want. Both the frontend and the backend run in the same container
* Frontend is for multiple servers installations. In this case, you'll have to provide a list of backend servers that the test will connect to
* Backend is for multiple servers. Use this to create test points to use in your frontend. It has no UI whatsoever

**Comment by adolfintel** [comment]
I'll be here if you need more information
