### ISSUE TITLE
how to use the same tool to test against multiple ISP Connections

### ISSUE THREAD

**Issue by techwizardg** [librespeed/speedtest#272]
Is there a way to use this tool to speed test against multiple ISP Connections? If so do let us know

**Comment by adolfintel** [comment]
Do you mean your client having multiple internet connections and being able to choose which one to use?

**Comment by techwizardg** [comment]
The network is made of multiple ISPs providing connection and we have servers connected to these ISPs and i want to simultaneously check the line status of all 4 ISPs, jitter, throughput - upload/download speed. How can i use this tool to achieve the same?

**Comment by adolfintel** [comment]
You can't, not until I make the command line client. You can use iperf to do this though.

**Comment by techwizardg** [comment]
When is the command line planned for release? i shall check iperf meanwhile

**Comment by adolfintel** [comment]
Some time in the future. Could be next month or next year. LibreSpeed isn't my job unfortunately so I only work on it when I have time

**Comment by techwizardg** [comment]
thanks and any pointers on how to use iperf

**Comment by techwizardg** [comment]
or any other tool that will provide output for multiple ISPs
