### ISSUE TITLE
Test initial ping multiple times and calculate average

### ISSUE THREAD

**Issue by paz** [librespeed/speedtest#273]
## Description
The results are sometimes inaccurate and an average value from 2-3 tests would fix this.
This should be a configurable option, choosing amount of tests (1 being how it is by default, right now, and a value of users choice for tests to average)

## Why it should be implemented
In my use case I use speedtest to pick best server for customer so they can see the fastest location for them, the automatic server selection is not always accurate however ( due to ping not averaged )

**Comment by adolfintel** [comment]
Are you talking about the server selector? It already does 3 pings.

**Comment by paz** [comment]
oh true my bad
