### ISSUE TITLE
Pass all settings through env variables

### ISSUE THREAD

**Issue by benjamin-bergia** [librespeed/speedtest#274]
## Description
I would like to be able to pass all the app settings and credentials through environment variables when using the docker image.

## Why it should be implemented
I am currently running this app on kubernetes with the servers.json and telemetry_settings.php in configmaps. Having credentials/settings in files make it hard to use kubernetes secrets. 

## Optional: implementation suggestions
Some of the settings are already available as environment variables. It should be possible to extend this setup to all settings. Namespacing the variables with something like the `LIBRETEST_` prefix might also be nice

**Comment by aptalca** [comment]
fyi, the [linuxserver image](https://github.com/linuxserver/docker-librespeed) allows you to configure most of the basics via docker env vars

**Comment by benjamin-bergia** [comment]
Thanks, I didn't know about this one.
