### ISSUE TITLE
Is there any way of getting MB/s instead of Mbps?

### ISSUE THREAD

**Issue by lexterror** [librespeed/speedtest#275]
I wanted to know how I could get MB/s.

Thank you!

**Comment by adolfintel** [comment]
Internet speed is usually measured in megabits per second. You can easily modify the UI to convert it to megabytes per second.
If you're using example-singleServer-full.html, for example:
* At lines 98 and 100, divide uiData.dlStatus and uiData.ulStatus by 8
* At lines 294 and 300, replace Mbps with MB/s
