### ISSUE TITLE
Any chance of supporting FreeBSD?

### ISSUE THREAD

**Issue by 2fst4u** [librespeed/speedtest#278]
## Description
It would be good if there was a supported version for FreeBSD as many people use FreeNAS for self hosting.

## Why it should be implemented
Everyone who uses FreeNAS would appreciate it greatly. It would be especially good if it were a package.

**Comment by adolfintel** [comment]
I haven't tested it personally, but it should work on FreeBSD, are you having trouble with it?

**Comment by 2fst4u** [comment]
I can't seem to find how exactly to install it. I know this isn't the place
for troubleshooting but maybe a readme for FreeBSD would be good?

**Comment by adolfintel** [comment]
A basic installation is the same as linux: install Apache2 and PHP7 and dump the files in the web server's root directory.

**Comment by 2fst4u** [comment]
I've got it mostly working, the main issue is the directories are pretty different for FreeBSD and Linux for the Apache install.

The IP detection script doesn't seem to be working properly, it's just outputting the entire contents of the script where it should be showing my IP. Is this potentially because I'm missing another dependency?

**Comment by adolfintel** [comment]
That happens if PHP is not enabled

**Comment by 2fst4u** [comment]
That appears to be the case. I'll work on that. Thanks.
