### ISSUE TITLE
Change gauge meter desine

### ISSUE THREAD

**Issue by ajaydabas** [librespeed/speedtest#279]
## Description
Change the gauge meter skin like other speed test

## Why it should be implemented
Who it would benefit, ...

## Optional: implementation suggestions
If you have experience in this field, feel free to give us suggestions

## Optional: screenshots
Add some screenshots, mockups, ... if they help clarify what you want
![images](https://user-images.githubusercontent.com/60464592/74699470-c2e14700-5226-11ea-840d-32b6b4211a5f.jpeg)

**Comment by adolfintel** [comment]
The included examples are just examples, the code needs to be as simple as possible so people can understand how to use the test and make their own UI, I can't complicate them by adding fancy gauges. You can easily do it yourself by modifying one of the examples though.
