### ISSUE TITLE
Minify speedtest.js

### ISSUE THREAD

**Issue by Perflyst** [librespeed/speedtest#283]
## Description
speedtest.js should be minified to be faster in production.

## Why it should be implemented
0.15s faster loading according to google pagespeed

**Comment by adolfintel** [comment]
If you look in the project's history, you'll see that it came with minified js files, which were loaded by the examples. People were always modifying the unminified files and complaining that their changes had no effects, so I got rid of the minification.
We would need some way to automate the generation of these files, but that would make things too complicated for the people who had the aforementioned problem. Got another idea?

**Comment by Perflyst** [comment]
You could provide both, minified and normal version, in the repo. Dunno if this would be too much work for you or something you dont want in general.
Since it is already quite fast we can also just ignore it. It is not like that it loads 1s faster, it is only 0.15s according to google.
If you decided in the past for good reasons to not minify it - ok. Now people who have the same question can find this issue ;)

**Comment by adolfintel** [comment]
I had both versions, that's what generated the confusion. People would edit speedtest_worker.js and then wonder why nothing happened. It was way more common than you'd think, even though the documentation clearly explained how to generate the minified version.

**Comment by Perflyst** [comment]
okay, then i will close this, thanks
