### ISSUE TITLE
Gauge moves, but doesn't measure/no results appear

### ISSUE THREAD

**Issue by user897943** [librespeed/speedtest#284]
## Description
A short description of what's going on

The measuring gauge moves the flat bar at the bottom of the arc when I press Start, but no numbers appear, it remains as ... on the gauge. It does sort of work on the Upload but it's clearly wrong, it should be something around 20MBps but it's currently 12.

## Server
Every info you can provide about your server: web server, database, PHP version, ... as well as server-side speedtest settings
If possible, provide an URL to your speedtest so we can check it

Running latest docker image on Raspberry Pi 4GB

## Client
Browser, OS, type of connection, unusual software, ...

Tested on latest version of Chromium MS Edge, Google Chrome, Mozilla Firefox, Chrome on Android.

## Steps to reproduce
* Do this
* Do that
* Bad stuff happens

Click start... bar moves but no result for download and inaccurate result for upload. Ping and jitter appear to be measured normally.

## Expected behaviour
What should have happened

Measure download and upload speed accurately and make the UI reflect the value.

I am using this on my LAN to test speed between devices on the LAN and my router. My router is providing AX/WiFi 6 speeds around the house varying from a minimum of 600Mbps up to around 1600Mbps. Some devices are also connected via gigabit ethernet to a Netgear switch which is then connected to the ASUS AX11000 AX router. I know there is an issue because running an internet speed test on fast.com or speedtest.net will yield greater results than the LAN speed test which should actually be much faster than my internet plan.

## Screenshots
If necessary, add screenshots of the test. 
F12 > Network screenshots can be particularly useful
![Annotation 2020-03-10 150859](https://user-images.githubusercontent.com/5891221/76326847-210ec080-62e1-11ea-9a22-2ed8c0f3c48d.jpg)
![Annotation 2020-03-10 151103](https://user-images.githubusercontent.com/5891221/76327044-67641f80-62e1-11ea-95df-d5d2239fa874.jpg)

**Comment by adolfintel** [comment]
Yes, it's clearly measuring an incorrect speed, and we need to find out why.
Write me at info@fdossena.com and I'll help you troubleshoot it, issues are only for bug reports (and obviously, I wouldn't have released it if it was in this state)
