### ISSUE TITLE
Graphing speedtest results

### ISSUE THREAD

**Issue by solarmon** [librespeed/speedtest#285]
## Description
I would like to be able to graph the download and upload figures.

I just need a very basic speedtest that returns just the download and upload figure so that a script can be used to feed those values in to the monitoring solution. It doesn't need to provide any progress updates.

The script could probably use wget or curl to call the page and then process the returned values and feed it to the monitoring solution.

Is it possible to have such a minimal speedtest page that does this with the current LibreSpeed solution?

## Why it should be implemented
Graphing the download and upload values will provide data for trending, analysis and troubleshooting.

**Comment by adolfintel** [comment]
You should be able to use our command line client to gather the data to make those charts: https://github.com/librespeed/speedtest-cli
If you need help with it you can ask me or @maddie
