### ISSUE TITLE
Proyect in laravel, how save a new variable in the mysql database

### ISSUE THREAD

**Issue by agaitan026** [librespeed/speedtest#287]
Hi i have a laravel website (user panel) where im showing the speedtest but in that laravel site i need to pass thru two variables (user_id and name) i tried this:

`		s.onend=function(aborted){
		  var user_id = {!! json_encode((array)auth()->user()->id) !!};
          var name= {!! json_encode((array)auth()->user()->name) !!};
          speed.innerHTML = "<img src=\"https://dbsnetwork.net/speed/results/telemetry.php?&user_id=" + user_id + "&name="+ name+ "\" width=1 height=1>";`

and it works but its creating two entries in mysql database like this:

<a href="https://ibb.co/TvJ113P"><img src="https://i.ibb.co/w0877mp/Screen-Shot-2020-03-29-at-9-14-45-PM.png" alt="Screen-Shot-2020-03-29-at-9-14-45-PM" border="0"></a>

**the last two fields are the new i just created (user_id and name)**

in the image the last entry have the correct info user_id and name but the first one have NULL

and also i changed telemetry.php:

and insert this two lines:

```
 $user_id = $_REQUEST['user_id'];
 
 $nombre = $_REQUEST['nombre'];`
```
Im trying to save the user_id and name from the user portal (laravel) to the mysql database
what im doing wrong? please help me and sorry for my english.

thank you

**Comment by adolfintel** [comment]
Instead of modifying the test, you should use the extra field that's already present in the db.
Put your data in an object, use JSON.stringify to turn it into a string, and pass it to the test using setParameter("extra",yourString)

You can retrieve your object later with JSON.parse.

Contact me at info@fdossena.com if you need help.
