### ISSUE TITLE
HTTPS slows down test

### ISSUE THREAD

**Issue by RomainL972** [librespeed/speedtest#288]
Hello, I have the Speedtest server installed on a RaspberryPi 4 connected with a wired gigabit Ethernet to the LAN. When I run the speedtest using the HTTP protocol from another computer, I get 879 and 945 Mbps. When I run the same test using HTTPS, I get 551 and 464 Mbps. Is it a problem with the speedtest or is the HTTPS protocol really slowing down the connection?

**Comment by adolfintel** [comment]
The problem is almost certainly the raspberry, I don't think it's fast enough to encrypt data at 1gbps.
If you want to be sure, run the test while looking at htop on the raspi, if you see high CPU usage, that's your problem.

**Comment by maddie** [comment]
@RomainL972 Out of curiosity, which backend did you use?

**Comment by RomainL972** [comment]
I used example-singleServer-full, is that what you are talking about?
