### ISSUE TITLE
file_get_contents fails when behind web proxy

### ISSUE THREAD

**Issue by tyronewyatt** [librespeed/speedtest#289]
I've been using your Speedtest for a while now but still have issues when running as it won't start the speedtest until file_get_contents times out after 30/60 seconds. 

I've got it running on IIS on server 2016/2019 with PHP 7.2

Clients are using Chrome or Edge

I am forced to use a http web proxy for all outgoing connections.

My workaround is to lower the default_socket_timeout to 1 second and restore it at the end of script after file_get_contents in getip.php.

**Comment by adolfintel** [comment]
That's because getIP.php tries to connect to ipinfo.io to get the ISP name. If you set a default proxy for that machine, it will work properly; alternatively, disable ISP detection (see wiki, custom settings)

**Comment by tyronewyatt** [comment]
No joy with the system proxy on IIS. I understand the use case where someone needs a HTTP proxy for outbound web requests on a website is fairly limited but this was my work around.

Add the following to getIP.php, I add this before the line 28. $ip = preg_replace("/^::ffff:/", "", $ip);

```
// Custom HTTP proxy support
$aContext = array(
    "ssl"=>array(
        "verify_peer"=>false,
        "verify_peer_name"=>false,
    ),
    'http' => array(
        'proxy'           => 'tcp://10.135.12.19:800', // set your HTTP proxy server here
        'request_fulluri' => true,
    ),
);
$cxContext = stream_context_create($aContext);
```


Update these two lines in getIP.php from:
```
$json = file_get_contents("https://ipinfo.io/" . $ip . "/json".getIpInfoTokenString());
$json = file_get_contents("https://ipinfo.io/json".getIpInfoTokenString());
```

To:
```
$json = file_get_contents("https://ipinfo.io/" . $ip . "/json".getIpInfoTokenString(), False, $cxContext);
$json = file_get_contents("https://ipinfo.io/json".getIpInfoTokenString(), False, $cxContext);
```
