### ISSUE TITLE
Add ability to change Apache port in Docker image

### ISSUE THREAD

**Issue by ingenieurmt** [librespeed/speedtest#290]
## Description
I'd like to add the ability to change the Apache port in the speedtest Docker image.

## Why it should be implemented
This would be useful for users who would like to run this image with `network_mode: host` to permit user IP addresses to display correctly, but don't want to run the image on port 80 (e.g. running behind a reverse proxy with multiple other services).

## Optional: implementation suggestions
PR will be submitted referencing this issue.

**Comment by adolfintel** [comment]
Can't you already do this by adding -p yourPort:80 to the docker run command?

**Comment by ingenieurmt** [comment]
Hi @adolfintel, unfortunately it's not quite the same thing. `-p yourport:80` simply forwards the port between the Docker network gateway and the container. This results in the IP address displayed by the speedtest page being that of where the container sees the request coming from, in this case the Docker network gateway (see the screenshot below for an example). Being able to set the Apache port allows you to attach the container directly to the host network interface using a port other than 80, which resolves this problem by removing the Docker network entirely.

![830047D2-86CA-4CDD-ACB1-7C2B310754BD](https://user-images.githubusercontent.com/1856537/78109049-d691e700-743b-11ea-8d16-4c7806cdb5ac.png)

**Comment by ingenieurmt** [comment]
![3071815E-21EC-45F4-9DEB-A2339ACBAF71](https://user-images.githubusercontent.com/1856537/78109171-12c54780-743c-11ea-91f7-3b8a3e90ef10.jpeg)

**Comment by adolfintel** [comment]
Ok, I'll merge your PR then
