### ISSUE TITLE
Amount of data uploaded/downloaded for test 

### ISSUE THREAD

**Issue by akhilleusuggo** [librespeed/speedtest#292]
## Description
Where can I change the amount of data downloaded/uploaded ?

## Why it should be implemented
To give more accuracy results

## Optional: implementation suggestions
looking for the location in the script .
I don't know where to ask it . But the owner should have this option and decide how much the speedtesters wants them to download/upload data amount for test .

## Optional: screenshots
Add some screenshots, mockups, ... if they help clarify what you want

**Comment by adolfintel** [comment]
Using a fixed amount of data is a bad idea in general and won't be implemented. Think about it: if the download test transfers 100MB of data, it will take several minutes on a slow connection, but it will take 1 second on a gigabit connection, which is too short, and you'll get an inaccurate measurement.
The test doesn't transfer a fixed amount of data, it has a time limit for the download and upload tests, and by default, the time it takes to run the test changes according to the measured speed (for instance, if you're on a slow 3G connection, it will take about 15 seconds, but if you're on gigabit ethernet, it will take about 3 seconds).
If for some reason you want to increase the duration of the tests, you can do it (see the wiki, custom frontends), this will also increase the calculated automatic duration (for instance, if you double the max duration, it doubles the automatically calculated duration as well). You can also disable the automatic duration and it will run for the max duration (default 15s).

**Comment by akhilleusuggo** [comment]
@adolfintel Thank you for the explanation . I got what you mean and you're right . So maybe the time duration is what I'm looking for . 
I'll take a look on the wiki . Thank you for taking the time to read .

**Comment by akhilleusuggo** [comment]
But I'm not understanding it well 
![image](https://user-images.githubusercontent.com/52116577/78214079-fc130500-74bc-11ea-94e7-6b34abcd4956.png)

If I replace or add `s.setParameter("parameter_name",value);` the test doesn't start .
There's any example on how it should look ?

**Comment by adolfintel** [comment]
Yes, there are examples and you're using one. All those parameters need to be set with s.setParameter, like this:
```
s.setParameter("time_dl_max",30);
s.setParameter("time_ul_max",30);
s.setParameter("time_auto",false);
s.setParameter("count_ping",10);
```
Note that 30 seconds is a really long time, most users will probably interrupt the test before it finishes.

**Comment by akhilleusuggo** [comment]
Oh nice , works! 
No 30s is too long I know . I've made it to see if it works . 
I want 10s

Thank you for the support/help !
