### ISSUE TITLE
this script detects the client's IP address and fetches ISP info from ipinfo.io/ Output from this script is a JSON string composed of 2 objects

### ISSUE THREAD

**Issue by neuyu** [librespeed/speedtest#294]
## Description
I follow the video, but something wrong. https://fdossena.com/?p=speedtest/quickstart_v5_ubuntu.frag 

![image](https://user-images.githubusercontent.com/16551927/78231951-24732180-7506-11ea-9d17-813782ec9491.png)

## Client
Chrome 80.0.3987.162
MacOS 10.15.2

**Comment by adolfintel** [comment]
You didn't install PHP, try again

**Comment by Cereal916** [comment]
This is exactly what I'm seeing, but I have PHP installed. It must not be playing nice with nginx.
