### ISSUE TITLE
Inaccurate browser testing results vs CLI results

### ISSUE THREAD

**Issue by linuxjunky** [librespeed/speedtest#297]
## Description
When testing against this server I get different results using different browsers: Chrome, Firefox, Edge. Upload typically shows 0.00Mbps. 
Using the CLI binary from the same windows client, I get consistent accurate results.

## Server
Speedtest server set up on Ubuntu 18.04 LTS following the video guide on the GIT page.

## Client
Windows 10 Pro.
Chrome
Firefox
M$ Edge
CLI Client - (librespeed-cli_1.0.4_windows_amd64) with local servers.json file

## Steps to reproduce
Browse to the server. Click Start
Using cli: librespeed-cli.exe --local-json public.json
Browser test results are inaccurate, varying greatly. Either Download or Upload shows 0.00Mbps depending on which browser you use. CLI test results are consistent, clightly lower than actual bandwidth available.

## Expected behaviour
Browser should report consistent results (somewhat) on par with the cli-based testing binary.

## Screenshots
![image](https://user-images.githubusercontent.com/31102118/78467206-4e268580-775e-11ea-9a9c-e9e358222aae.png)
![image](https://user-images.githubusercontent.com/31102118/78467072-14a14a80-775d-11ea-8a83-d76990c87a3f.png)
![image](https://user-images.githubusercontent.com/31102118/78467084-27b41a80-775d-11ea-9ebf-1d6a42ab36e4.png)
![image](https://user-images.githubusercontent.com/31102118/78467176-ed974880-775d-11ea-8dc7-11135aca4a8a.png)

**Comment by adolfintel** [comment]
That's strange. Contact me at info@fdossena.com and I'll help you troubleshoot it.
