### ISSUE TITLE
realtime graph of the tested parameters

### ISSUE THREAD

**Issue by kotc** [librespeed/speedtest#298]
## Description
can you add bunch of graphs (dl, ul, ping, jitter) that show how parameters fluctuate over time. might be useful to use one graph for everything so it would be easily shareable

## Why it should be implemented
everyone that's troubleshooting network bandwidth

## Optional: implementation suggestions
could be generated via dynamic svg, probably, similarly to the way openwrt shows their graphs

**Comment by adolfintel** [comment]
We're already working on a new frontend, with charts :)

**Comment by kotc** [comment]
great! is it available somewhere or just offline work in progress?
