### ISSUE TITLE
RHEL8 (possibly CentOS8) getIP.php not returning client IP Address

### ISSUE THREAD

**Issue by mekisiel** [librespeed/speedtest#299]
First, apologies for having limited info at this point in time. Wanted to log an issue regardless, if this was known or if I'm missing something obvious. Happy to provide additional information, as necessary. Will continue to poke at it as well.

[RHEL8]$ httpd -v
Server version: Apache/2.4.37 (Red Hat Enterprise Linux)
Server built:   Sep  2 2019 14:31:45
[RHEL8]$ php -v
PHP 7.2.11 (cli) (built: Oct  9 2018 15:09:36) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

Speedtest version 5.2

[RHEL7]$ httpd -v
Server version: Apache/2.4.6 (Red Hat Enterprise Linux)
Server built:   Oct  8 2019 05:47:38
[RHEL7]$ php -v
PHP 5.4.16 (cli) (built: Oct 29 2019 09:56:22)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies

Speedtest version 5.2

Clients:
Chrome Version 80.0.3987.163 (Official Build) (64-bit)
and
Firefox 68.5.0esr (32-bit)

Issue:
Client IP Address does not get displayed in the IP Area when using Speedtest deployed on RHEL8 (single or multi-server with RHEL8 as a backend). No issues with a RHEL7 deployment. Suspect a PHP version issue (given the version discrepancy), but haven't dug too deep or attempted to downgrade RHEL8 to 5.4.16. Also suspect that this could be reproduced with CentOS7 and 8 (for ease of non-RH troubleshooting), but have not attempted that either.

**Comment by maddie** [comment]
If configuring different PHP versions on the server is too difficult, you can try the Go version and see if it works for you.

**Comment by adolfintel** [comment]
What does it output instead of the IP?

**Comment by mekisiel** [comment]
The output is null. Nothing is displayed in the ipArea.

**Comment by adolfintel** [comment]
Delete line 7 from getIP.php, run it, and see if anything appears in the server logs.

**Comment by mekisiel** [comment]
/var/log/php-fpm/www-error.log
[08-Apr-2020 12:54:00 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function json_encode() in /var/www/html/backend/getIP.php:151
Stack trace:
#0 {main}
  thrown in /var/www/html/backend/getIP.php on line 151

Apparently PHP 7.2.11 doesn't include native JSON support.
Installed via yum install php-json.
Restarted httpd service.
The client's IP Address is now displayed.

Thanks for pointing me in the right direction.

**Comment by adolfintel** [comment]
The json module is usually preinstalled when you install PHP, we'll add it to the documentation
