### ISSUE TITLE
apt-get问题

### ISSUE THREAD

**Issue by liuguoqing0929** [librespeed/speedtest#301]
apt-get是否只适合ubuntu不适用于centos呢？你有没有centos的版本呢

**Comment by maddie** [comment]
Please use English in the issue tracker.

What do you mean by using `apt-get`? I'm not sure about the question you're asking.

If you're using CentOS, you can always adapt to use `yum` or `dnf`. Instructions for installing packages should be easily available via Google.

Closing this issue for now.
