### ISSUE TITLE
Microsoft Defender ATP - T1094 - Outbound connection to ip address with a history of unauthorized access attempts

### ISSUE THREAD

**Issue by maxleonalbrecht** [librespeed/speedtest#305]
## Description

Microsoft Defender ATP shows the following:

![image](https://user-images.githubusercontent.com/8051297/79227436-29b66180-7e60-11ea-9719-d63eae8cbe96.png)

It states that the IP's behind lux1.backend.librespeed.services and ny1.backend.librespeed.services with the IP 104.244.78.231 and 199.195.251.84 have malicious history.

Connected to the following article: https://attack.mitre.org/techniques/T1094/

**Important:** I clearly think this a false positive, but it maybe impacts users, which use the very nice speedtest on coporate devices.

## Server
n/a

## Client
Microsoft Edge Version 84.0.480.0 (Official build) canary (64-bit)
Microsoft Windows [Version 10.0.18363.720]

## Steps to reproduce

- Take a speedtest and take a log of device alerts in ATP

## Expected behaviour
No error messages in ATP

**Comment by adolfintel** [comment]
It's obviously a false positive. I forwarded this issue to the owners of those servers to see if they can do something about it.

**Comment by maxleonalbrecht** [comment]
Thank you!
