### ISSUE TITLE
root path

### ISSUE THREAD

**Issue by liuguoqing0929** [librespeed/speedtest#307]
## Description
After I installed it successfully,The default path is 127.0.0.1:80，If I want to set the path as 127.0.0.1:80/speedtest, How should I set up the Dockerfile

## Why it should be implemented
How should I set it

## Optional: implementation suggestions
If you have experience in this field, feel free to give us suggestions

## Optional: screenshots

![image](https://user-images.githubusercontent.com/56615408/79618297-3f67a780-813c-11ea-93ba-964fde5d34af.png)
![image](https://user-images.githubusercontent.com/56615408/79618326-4e4e5a00-813c-11ea-91a0-fc7d0553370e.png)

**Comment by maddie** [comment]
Setting the path for the speed test page isn't supported by the Docker image for now. 

You can either:

- Submit a PR for this feature
- Bind Docker to another port and set up a reverse proxy (e.g. nginx, Apache, Caddy) to access it under another path

If you don't know how to modify the Docker image to suit your needs, I'd recommend you search through [Docker's official documentation](https://docs.docker.com/get-started/), as it is out of scope for discussion here.

**Comment by adolfintel** [comment]
Using a reverse proxy is the best solution in my opinion. Docker images usually provide a "bare" HTTP server and you use a reverse proxy to provide HTTPS, routing, etc.
