### ISSUE TITLE
path

### ISSUE THREAD

**Issue by liuguoqing0929** [librespeed/speedtest#309]
## Description
My initial path is 127.0.0.1:80, I use nginx to map the path to https://cwyth-uat.cscec.com/speedtest. The page can be loaded, but An error is reported for the js reference to index.php. How can I solve this problem
## Why it should be implemented
How can I solve this problem

## Optional: screenshots
![image](https://user-images.githubusercontent.com/56615408/79704341-8cd24900-82e3-11ea-827c-9eb76012a746.png)

**Comment by maddie** [comment]
Can you post the actual error from your Chrome console?

This is most likely an Nginx configuration problem.

**Comment by liuguoqing0929** [comment]
Nginx&nbsp;can run. The page load successful.&nbsp; when i set path&nbsp;https://cwyth-uat.cscec.com/&nbsp;for my project path, it can be successful.&nbsp;https://cwyth-uat.cscec.com/speedtest can not run.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"maddie"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月20日(星期一) 上午9:14
收件人:&nbsp;"librespeed/speedtest"<speedtest@noreply.github.com&gt;;
抄送:&nbsp;"风雪"<302650374@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [librespeed/speedtest] path (#309)





 
Can you post the actual error from your Chrome console?
 
This is most likely an Nginx configuration problem.

**Comment by maddie** [comment]
Still, this is most likely your Nginx configuration problem.

I have deployments behind Nginx with subpaths running without any problem.

**Comment by liuguoqing0929** [comment]
Could you please provide me with your&nbsp; nginx.conf






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"maddie"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月20日(星期一) 上午9:53
收件人:&nbsp;"librespeed/speedtest"<speedtest@noreply.github.com&gt;;
抄送:&nbsp;"风雪"<302650374@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [librespeed/speedtest] path (#309)





 
Still, this is most likely your Nginx configuration problem.
 
I have deployments behind Nginx with subpaths running without any problem.

**Comment by liuguoqing0929** [comment]
https://cwyth-uat.cscec.com/SPEEDTEST&nbsp;is my path.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"maddie"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月20日(星期一) 上午9:53
收件人:&nbsp;"librespeed/speedtest"<speedtest@noreply.github.com&gt;;
抄送:&nbsp;"风雪"<302650374@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [librespeed/speedtest] path (#309)





 
Still, this is most likely your Nginx configuration problem.
 
I have deployments behind Nginx with subpaths running without any problem.

**Comment by maddie** [comment]
```
server {
	listen 8080;
	listen [::]:8080;
	server_name cwyth-uat.cscec.com;

	location /speedtest/ {
		proxy_set_header Host $http_host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-Host $http_host;
		proxy_set_header X-Forwarded-Server $http_host;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_pass http://127.0.0.1:80/;
	}
}
```

**Comment by liuguoqing0929** [comment]
thank you ,I've solved it


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"maddie"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月20日(星期一) 下午4:37
收件人:&nbsp;"librespeed/speedtest"<speedtest@noreply.github.com&gt;;
抄送:&nbsp;"风雪"<302650374@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [librespeed/speedtest] path (#309)





 server { 	listen 8080; 	listen [::]:8080; 	server_name cwyth-uat.cscec.com; 	location /speedtest/ { 		proxy_set_header Host $http_host; 		proxy_set_header X-Real-IP $remote_addr; 		proxy_set_header X-Forwarded-Host $http_host; 		proxy_set_header X-Forwarded-Server $http_host; 		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 		proxy_set_header X-Forwarded-Proto $scheme; 		proxy_pass http://127.0.0.1:80/; 	} }
