### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by Superbug50** [librespeed/speedtest#312]
## Description
A button that toggles a dark mode.

## Why it should be implemented
People who wants to run a speed test at night or anytime.

**Comment by adolfintel** [comment]
The examples on this project are just that, examples, to show developers how to integrate LibreSpeed into their existing website, they need to be as simple as possible, easy to understand and modify, there's no need to complicate them by adding different color schemes. If you want a dark theme, just change the CSS in the example you're using.

**Comment by BloodyIron** [comment]
For future humans to read, you can easily achieve a dark theme by adjusting the colour (hex/rgb) values in the CSS section of the example html files. It's very easy once you find where they are! (which is actually pretty easy to find). It may be a bit intimidating if you're not familiar with CSS, but once you get the hang of it, it's super easy peasy!

**Comment by torresjrjr** [comment]
I have a better solution.

I am aligned with the minimalist, "no BS" design philosophy of this project, and I'm therefore also against a button, which would require either some hacky or bloated client-side CSS, or JS.

My proposal: there exists a CSS media query called "prefers-color-scheme", which is entirely and easily user configurable (in the browser or system settings), requires no JS, has wide support amongst browsers (and subsequently has the benefit of redundancy), and does not need the developer to add complexity or bloat.

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

> If you want a dark theme, just change the CSS in the example you're using.

This isn't a solution. The requested button feature is about how the *user* can configure the CSS just for himself, not how the developer can change the CSS for all visitors. My proposal should solve this.

I will create a pull request demonstrating this soon.

**Comment by torresjrjr** [comment]
Here's an example I created with Inspector Mode in Firefox, from `example-singleServer-pretty.html`

```
--- librespeed-v1.css   2020-12-11 10:02:32.976057200 +0000
+++ librespeed-v2.css   2020-12-11 10:02:26.905174200 +0000
@@ -100,5 +100,14 @@
                        margin: 0 auto;
                }
        }
+       @media (prefers-color-scheme: dark) {
+               body {
+                       background:#0A0A0A;
+                       color:#CCCCCC;
+               }
+               h1 {
+                       color:#AAAAAA;
+               }
+       }

 </style>
```

Do you think this is a viable solution? If so, I'd be happy to see it as part of the examples, to encourage hosters to use it out of the box.

Let me know what you think.

**Comment by BloodyIron** [comment]
I'm not opposed to the "prefers-color-scheme" method, I simply wanted to post something I did that delivered a similar thing, so someone reading this had a possible solution, whether it's an interim solution, or whatnot. :)

**Comment by torresjrjr** [comment]
Sorry. I meant to direct my post to @Superbug50. I'm not sure what the most effective way to do that is. I guess a mention will do.
