### ISSUE TITLE
Set a donation goal to not need advertising/sponsorship anymore

### ISSUE THREAD

**Issue by tuxayo** [librespeed/speedtest#314]
It might be necessary now even to assure bare minimal maintenance of the software. But the proposal is to set the goal to not have advertising in the future (other than in the server list)

To reach such goal, an equal place should be given in the web page to the funding link. Which currently is not there at all.

**Comment by Perflyst** [comment]
We were already thinking about linking to a donation place on librespeed.org though this has nothing to do with the librespeed software itself ;)

Also we are thankful for any speedtest server sponsorship, it helps us and the sponsor!
