### ISSUE TITLE
"server" in SPEEDTEST_SERVERS not ping server 

### ISSUE THREAD

**Issue by theanhvo** [librespeed/speedtest#315]
I had config https for server speed test and updated "server": "http://fi.openspeed.org/" but server speed not ping to http://fi.openspeed.org/
Thank you !

**Comment by adolfintel** [comment]
I don't understand what you're saying, but you're not supposed to use that server, it's only for demonstration purposes. Follow the instructions on the wiki on how to set up your own LibreSpeed instance(s)
