### ISSUE TITLE
 Difference in Result of the Web Version for Mobile

### ISSUE THREAD

**Issue by jgarghetti** [librespeed/speedtest#317]
When testing on the mobile web the result is not even close to how much is tested on the desktop computer
![Web - Iphone](https://user-images.githubusercontent.com/64535525/80596841-63a96b00-89fd-11ea-99e9-1d4da1bdb5dd.jpeg)

![Web - Desktop](https://user-images.githubusercontent.com/64535525/80596869-6e640000-89fd-11ea-90d5-1758ffb4864e.png)

**Comment by adolfintel** [comment]
That's a massive difference, it's probably some weird configuration issue on your server. Please contact me at info@fdossena.com for troubleshooting
