### ISSUE TITLE
Java support

### ISSUE THREAD

**Issue by Jozoazhua** [librespeed/speedtest#322]
Hello, due to the limitations of the environment, can support Java. Or garbage.php using Java.

**Comment by adolfintel** [comment]
I don't understand your question.
You want a java backend or a java client?

**Comment by Jozoazhua** [comment]
> I don't understand your question.
> You want a java backend or a java client?

As long as it works in Java.

**Comment by adolfintel** [comment]
The currently maintained backends are PHP and Go, there is no Java backend if that's what you mean.
