### ISSUE TITLE
Auto start speedtest on website load?

### ISSUE THREAD

**Issue by nahventure** [librespeed/speedtest#324]
hello. I do not see an option to do this,
i would like it to where my user can load the page and it instantly starts taking a speedtest.
similar to that of fast.com's interface.

can I also somehow modify the gauges ? the fastest speeds we will allow are 50mbps so id like that to max out the meter.

**Comment by adolfintel** [comment]
Assuming you're using one of the full examples, just add onload="startStop()" to the <body> tag if you want it to start immediately. I think it's rude though.

The code for the gauges can be easily modified, just look for the comment that says //CODE FOR GAUGES. The formula you want to modify is probably function mbpsToAmount.
