### ISSUE TITLE
Download test gives slow results

### ISSUE THREAD

**Issue by motishaku** [librespeed/speedtest#325]
Hi!
First of all, thanks for a great speed test project.

We are trying to implement the speedtest in our offline network, while having some issues.

While executing the test, we get 4-6 Mb download and 100 MB upload.

After reviewing the troubleshooting thread, we made sure everything is fine, and that the garbage and empty files are reachable.

While testing bandwidth using iperf, the test results were always around 100Mb, which is fine as the clients are connected using 100 mb cables.

We looked through some closed issues but could not find a solution.

Would appreciate any help, thank you.

**Comment by adolfintel** [comment]
Hi,
You probably don't have PHP or its OpenSSL module installed or enabled.
Also, please don't use issues for troubleshooting, contact me at info@fdossena.com if you need help :)

**Comment by mikl0s** [comment]
For future reference - this also happens if your webserver aren't parsing the php properly. On FreeBSD with Apache you need to add the following to httpd.conf for libressl to properly work (or any PHP stuff really).

```
<FilesMatch "\.php$">
    SetHandler application/x-httpd-php
</FilesMatch>
<FilesMatch "\.phps$">
    SetHandler application/x-httpd-php-source
</FilesMatch>
```

**Comment by netomx** [comment]
What if I dont want to use PHP or OpenSSL? Is it possible to use this tester?
