### ISSUE TITLE
Hi team I need create speed for custom destination

### ISSUE THREAD

**Issue by davidandradeb** [librespeed/speedtest#326]
## Description
I have a server in GCP, I need test the all parameters from de client to my server.

## Why it should be implemented
Very important implementations

## Optional: implementation suggestions
Simply a setter with ip of server or name

THANKS

**Comment by adolfintel** [comment]
I'm not sure I understand. Do you want the user to be able to set the server address manually in the web UI?

**Comment by davidandradeb** [comment]
Hi @adolfintel , thanks for you response.

I need set IP target server for test, example:

I create a SaaS platform for contact center over WEB-RTC, so depends for internet connection, Jitter, and speed metrics.

Many users create tickets with problems are: cuts, echo and others issues with your calls and  most have network troubles. 

I need a speedtest from the client to my GCP server, and check all possible parameters.

How to ?

**Comment by adolfintel** [comment]
If all your servers have a librespeed backend installed (PHP or Go), only the UI needs to be modified. Basically, you can start with the multipleServers-full example and instead of having the hardcoded server list, you have a form where the user can input the server address.
If this is what you need, and you don't have the skills to do it, I can do it for you for a fee.

**Comment by davidandradeb** [comment]
Thanks @adolfintel in the example I change this

var SPEEDTEST_SERVERS=[

	{
	 name:"DYALOGO Interno",
	server:"//interno.dyalogo.cloud/",
	dlURL:"st_be/garbage.php",
	ulURL:"st_be/empty.php",
	pingURL:"st_be/empty.php",
	getIpURL:"st_be/getIP.php"
	},

But, I have this error:

example-multipleServers-full.html:1 Access to XMLHttpRequest at 'https://mpotdemo.fdossena.com/empty.php?cors=true' from origin 'https://interno.dyalogo.cloud' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

However the test run:

 
![image](https://user-images.githubusercontent.com/5994937/84393016-b0698f80-abc0-11ea-8b4a-4a784c144f95.png)

how to resolve CORS problem? the backend is over httpd.

**Comment by adolfintel** [comment]
mpotdemo.fdossena.com is down, to show that the test can detect it, that's why you're getting that error. It's nothing to worry about, besides, you should remove the demo servers in production.

**Comment by davidandradeb** [comment]
Perfect ! thanks very much.
