### ISSUE TITLE
At docker

### ISSUE THREAD

**Issue by Rogershanyu** [librespeed/speedtest#327]
journal : standard_init_linux.go:211: exec user process caused "exec format error"

**Comment by adolfintel** [comment]
What architecture are you running it on?

**Comment by Rogershanyu** [comment]
openwrt

**Comment by adolfintel** [comment]
Is it x86_64?

**Comment by Rogershanyu** [comment]
arm

**Comment by adolfintel** [comment]
The docker version only supports x86_64 at the moment. Some guy was trying to port it to other architectures but he never finished it. https://github.com/librespeed/speedtest/issues/267

**Comment by Rogershanyu** [comment]
But I can run other services

**Comment by adolfintel** [comment]
The problem is LibreSpeed, not your system.
If you can install Apache and PHP you can do a manual install and it will work.

**Comment by Rogershanyu** [comment]
ok thanks

**Comment by Rogershanyu** [comment]
My openwrt system can install Apache and PHP. Can I run on openwrt ?

**Comment by adolfintel** [comment]
Yes, some people have done it before.
You should need apache2, php, openssl (and its php module), php-gd, php-json, freetype2 (and its PHP module), and one of the supported databases (mysql, sqlite, postgresql. I'd recommend sqlite in this case)

**Comment by maddie** [comment]
You can also use Go version for a single binary + assets files deployment.

**Comment by ingenieurmt** [comment]
You can also use the [Docker buildx tool](https://docs.docker.com/docker-for-mac/multi-arch/)  to create a multi-arch build of the Docker image that will run on ARM.

**Comment by adolfintel** [comment]
@maddie is right, the Go version might run better if it's installed on a router or something low power.
@ingenieurmt Thank you, I'll take a look at it

**Comment by Rogershanyu** [comment]
fatal: not a git repository (or any of the parent directories): .git
go: downloading github.com/urfave/cli/v2 v2.1.1
go: downloading github.com/sirupsen/logrus v1.4.2
go: downloading github.com/gocarina/gocsv v0.0.0-20200302151839-87c60d755c58
go: downloading github.com/maddie/go-ping v0.0.0-20200311033510-5e9a13ec8da6
go: downloading github.com/briandowns/spinner v1.9.0
go: downloading golang.org/x/sys v0.0.0-20190422165155-953cdadca894
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.0-20190314233015-f79a8a8ca69d
go: downloading golang.org/x/net v0.0.0-20200226121028-0de0cce0169b
go: downloading github.com/russross/blackfriday/v2 v2.0.1
go: downloading github.com/fatih/color v1.7.0
go: downloading github.com/mattn/go-isatty v0.0.8
go: downloading github.com/mattn/go-colorable v0.1.2
go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
# runtime/cgo
exec: "gcc": executable file not found in $PATH

**What's the problem?**

**Comment by adolfintel** [comment]
I think you're inside the .git folder, go up one level

**Comment by Rogershanyu** [comment]
```
fatal: not a git repository (or any of the parent directories): .git
go: downloading github.com/urfave/cli/v2 v2.1.1
go: downloading github.com/sirupsen/logrus v1.4.2
go: downloading github.com/gocarina/gocsv v0.0.0-20200302151839-87c60d755c58
go: downloading github.com/maddie/go-ping v0.0.0-20200311033510-5e9a13ec8da6
go: downloading github.com/briandowns/spinner v1.9.0
go: downloading golang.org/x/sys v0.0.0-20190422165155-953cdadca894
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.0-20190314233015-f79a8a8ca69d
go: downloading golang.org/x/net v0.0.0-20200226121028-0de0cce0169b
go: downloading github.com/russross/blackfriday/v2 v2.0.1
go: downloading github.com/fatih/color v1.7.0
go: downloading github.com/mattn/go-isatty v0.0.8
go: downloading github.com/mattn/go-colorable v0.1.2
go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
#runtime/cgo
exec: "gcc": executable file not found in $PATH
```
What's the problem?

**Comment by maddie** [comment]
Can you tell me what commands did you run?

Also, try using CGO_ENABLED=0 with your build command, e.g.

```
CGO_ENABLED=0 go build ....
```

**Comment by Rogershanyu** [comment]
@maddie  ./build.sh

**Comment by Rogershanyu** [comment]
@adolfintel root@FriendlyWrt:/speed/speedtest-cli#  ./build.sh

**Comment by maddie** [comment]
Oh.. it seems you're building the CLI instead of the backend.

Follow the instructions [here](https://github.com/librespeed/speedtest/wiki/Installation-(Go))

**Comment by maddie** [comment]
And you can cross compile it for your router on your PC.

If you're building for, say ARMv7:

```
GOOS=linux GOARCH=arm GOARM=7 go build ....
```

**Comment by Rogershanyu** [comment]
@maddie 
```
cd .; git clone -- https://go.googlesource.com/dl /root/go/src/golang.org/dl
Cloning into '/root/go/src/golang.org/dl'...
fatal: unable to find remote helper for 'https'
package golang.org/dl/go1.14.2: exit status 128
```

**Comment by maddie** [comment]
Are you running this under OpenWrt? If you want to fetch `https` sources, you need `wget-ssl` or `curl` with openssl and ca-certificates/ca-bundle installed.

I'd recommend you to compile on your PC and copy it over to your router.

**Comment by Rogershanyu** [comment]
@maddie https://github.com/librespeed/speedtest-cli
Can't I use this

**Comment by adolfintel** [comment]
@maddie you might want to add binaries for the Go version to the releases like you did with the CLI version

**Comment by maddie** [comment]
@Rogershanyu that’s the CLI, not backend

@adolfintel I’ll do that ASAP, but it would be great if I can do it in a separate repo.

**Comment by Rogershanyu** [comment]
@maddie My computer install go?

**Comment by maddie** [comment]
@Rogershanyu Yes, you can compile it on your computer.

Or you can wait for a while, I'm going to release binaries for the backend soon.

**Comment by Rogershanyu** [comment]
ok 谢谢!

**Comment by maddie** [comment]
@Rogershanyu Binaries now availble here: https://github.com/librespeed/speedtest-go/releases/tag/v1.0.0

Be sure to copy the `assets` folder and `settings.toml` over with the binary to your router.

**Comment by Rogershanyu** [comment]
How do I use?

**Comment by maddie** [comment]
@Rogershanyu Download the appropriate binary for your router (e.g. Linux ARMv7 will use the `linux-armv7` binary, and put the `assets` folder and `settings.toml` alongside the binary. Give it approprite permission and run it (i.e. `chmod +x binary_name`)

If you have further questions you can reach me via Telegram (@maddiecn) or Matrix (@maddie:matrix.zzz.cat)
