### ISSUE TITLE
Hope to add arm-docker images

### ISSUE THREAD

**Issue by samondlee** [librespeed/speedtest#329]
We have more and more Arm v7 v8 devices with 1000M/lan port.

such as rpi,or something else, it's low cost and enviroment friendly.

my devices runs with armbian, and i want to deploy speedtest with docker too,

but i find this image can't deploy a speedtest...

so it's better to add a ARM docker image....

**Comment by mickkael** [comment]
@samondlee I have build a Dockerfile of the go version of librespeed (librespeed-go) here: https://github.com/librespeed/speedtest-go/pull/3
And I have compiled and upload to Dockerhub an arm64 version
https://hub.docker.com/r/mickkael/librespeed-go/tags

at least for Rpi, the go version is much faster, while the php version was maxing out the CPU and limiting the bandwidth.

**Comment by samondlee** [comment]
> @samondlee I have build a Dockerfile of the go version of librespeed (librespeed-go) here: [librespeed/speedtest-go#3](https://github.com/librespeed/speedtest-go/pull/3)
> And I have compiled and upload to Dockerhub an arm64 version
> https://hub.docker.com/r/mickkael/librespeed-go/tags
> 
> at least for Rpi, the go version is much faster, while the php version was maxing out the CPU and limiting the bandwidth.

Wow thanks,hope arm could replace x86 at server area more and more....we love eco friendly device....
