### ISSUE TITLE
Packet Loss?

### ISSUE THREAD

**Issue by voipuser** [librespeed/speedtest#331]
Hi folks

Great test you have created, thank you for sharing it with us all.

I was wondering if there was any way to test for packet loss? Some test tools on the market have this but I'm not sure if this can be done as part of your html5 test. It is very useful for VoIP testing to have a feel for packet loss, hence the question.

Thanks a lot.
Andy

**Comment by adolfintel** [comment]
Hi,
This was already asked many times, but it's currently impossible to implement in a reliable way because transport errors like packet losses are handled at the transport level and the application is not even aware of that.
