### ISSUE TITLE
In official Docker version of LibreSpeed file idObfuscation.php can't get permission to filesystem.

### ISSUE THREAD

**Issue by WildRat** [librespeed/speedtest#336]
## Description
In official **Docker** version of LibreSpeed if obfuscation is enabled procedures in file **/var/www/html/results/idObfuscation.php** can't get permission to filesystem.

## Server
It's official Docker version that has all this onboard. Installed on Ubuntu server 20.04.

## Client
Any. It's doesn't metter.

## Steps to reproduce
Install Docker version of LibreSpeed with standart settings including obfuscation enabled.
Do speed test.
There is no results box and no telemetry record.

## Expected behaviour
Result are showed onscreen and loged in telemetry db.

## Screenshots
Developer console shows:
`Warning: fopen(/var/www/html/results/idObfuscation_salt.php): failed to open stream: Permission denied in /var/www/html/results/idObfuscation.php on line 8

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/html/results/idObfuscation.php on line 9

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/html/results/idObfuscation.php on line 10

Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/html/results/idObfuscation.php on line 11

Warning: fclose() expects parameter 1 to be resource, boolean given in /var/www/html/results/idObfuscation.php on line 12

Warning: require(/var/www/html/results/idObfuscation_salt.php): failed to open stream: No such file or directory in /var/www/html/results/idObfuscation.php on line 13

Fatal error: require(): Failed opening required '/var/www/html/results/idObfuscation_salt.php' (include_path='.:/usr/local/lib/php') in /var/www/html/results/idObfuscation.php on line 13`

**Comment by adolfintel** [comment]
Confirmed.
This must have been introduced by one of the base images. Will fix this asap

**Comment by adolfintel** [comment]
Fixed, the new build will be available on docker hub soon
