### ISSUE TITLE
Second "start/stop"-button for automated tests

### ISSUE THREAD

**Issue by sebaro11** [librespeed/speedtest#339]
## Description
On the frontend side add another button and field for automated speedtests. I have set up a librespeed instance for mapping my celluar network and want to test the speed while driving around. If there is a button that automatically starts a new speedtests after the last one was finished (with like a couple of seconds pause in between) that would make my mapping very comfortable. 

## Why it should be implemented
People who need many automated tests for measurements etc.

## Optional: implementation suggestions
I'm not really a programmer, but I think it could be made with another button and an input field for the number of automated tests. It just needs to call a new speedtest on the Javascript.

**Comment by adolfintel** [comment]
This is very specific to your use case, but it can be implemented without any major changes, it's basically just a custom frontend.

If you would like to have it implemented contact me at info@fdossena.com, I'm sure we can work out a deal :)
