### ISSUE TITLE
The test result is no good.

### ISSUE THREAD

**Issue by mbj2014** [librespeed/speedtest#340]
## Description
using docker from last ver, browser in the server, download and up speed only 100Mbps, Ping 3 ms? I think it will be more then 1000Mbps and less then 1ms.

## Server
docker engine 19.03.12, Mac OS Catalina 10.15.6,  chrome 83.0.4103.97

## Client
chrome 83.0.4103.97

## Steps to reproduce
docker run -p 80:80 adolfintel/speedtest
visit web，click Start button.

## Expected behaviour
speed is to low

## Screenshots
If necessary, add screenshots of the test. 
F12 > Network screenshots can be particularly useful
![image](https://user-images.githubusercontent.com/6398791/88861879-81bb7d00-d231-11ea-80c7-c9b3dec52cdd.png)
![image](https://user-images.githubusercontent.com/6398791/88862055-e8409b00-d231-11ea-8e61-af4b8c93f328.png)

**Comment by mbj2014** [comment]
![Speedtest1](https://user-images.githubusercontent.com/6398791/88862185-2ccc3680-d232-11ea-8bdf-f64812e84196.jpg)

**Comment by adolfintel** [comment]
Hmm, definitely can't reproduce this, but I don't have a mac.
What can you tell me about your setup? Are you running the test over wifi or ethernet?

**Comment by mbj2014** [comment]
In Windows，can get same result.

you can test this in same computer.

**Comment by adolfintel** [comment]
What's between you and the server? How do you connect?

**Comment by mbj2014** [comment]
all test in one computer.

the docker and browser in one computer.

I think both of then in one computer, the test data transfer all in memory，so the speed should fast more then 1000Mbps
