### ISSUE TITLE
Allow query of User Name or Email

### ISSUE THREAD

**Issue by yurividal** [librespeed/speedtest#349]
## Description
Hi. We are using librespeed internally, to test the quality of our emplyees' home connection, in order to facilitate working from home. It would be great if there was an option for the user to put his name (or email), and that would get stored in the database, for engineers to refference. This way, users dont have to manually submit their results. Its for internal use only. Could be enabled by a flag?

## Why it should be implemented
With the covid, many companied, schools etc, are shifting towards home-office and remote working. Being able to assess colaborator's internet and identifying potential problems would be great for IT departments.

**Comment by adolfintel** [comment]
Hi,
If you look in the documentation, there's an extras field that can be passed to the test that can contain pretty much anything. This was added specifically to support this kind of custom UIs: you just add your form to the page and when the start button is pressed, you can do this:
```js
var mydata={};
mydata.name=document.getElementById("name");
...
s.setParameter("telemetry_extra",JSON.stringify(mydata));
```
Telemetry must be enabled, of course.

If you don't know how to do it, contact me at info@fdossena.com and I'll do it for you in exchange for a donation.

**Comment by yurividal** [comment]
Thanks! Actually, that was exactly what i did, and it is working fine. The request was more for making this easier, perhaps pre-implementing it, and enabling/disabling with a single toggle or flag.
