### ISSUE TITLE
about the validation of download and upload speed

### ISSUE THREAD

**Issue by moveen1999** [librespeed/speedtest#350]
hey,
we successfully host the tool but there is an issue with the download and upload speed. it varies with the tool iperf. we are using a VPN network if you can please help us to resolve this problem.
sometimes the tool displays more speed than in link.

**Comment by adolfintel** [comment]
If it's off by a small amount you may have to change (or disable) overheadCompensationFactor. By default this is set to 1.06, set it to 1 to disable it.

If you need more help troubleshooting this, write me at info@fdossena.com
