### ISSUE TITLE
Add a Packet-loss test

### ISSUE THREAD

**Issue by yurividal** [librespeed/speedtest#352]
## Description
Hi. I would like to suggest a packet-loss test, similar to https://packetlosstest.com/

## Why it should be implemented
It is a great extra tool to have, specially for VoIP, Video, Telepresence and Gaming servers.

## Optional: implementation suggestions
These guys have it really nicely implemented: https://packetlosstest.com/

**Comment by adolfintel** [comment]
Packet loss can't be measured over HTTP or even websockets (they work over TCP).
We could do it with WebRTC but that then you wouldn't be able to install LibreSpeed on any PHP hosting like we do today. Maybe in the future, when QUIC becomes common, we'll be able to find some trick to do it.

**Comment by mirh** [comment]
A trick like [this one](http://cseweb.ucsd.edu/~savage/papers/Usits99.pdf)?
As a guy that had the web timeout like there was no tomorrow on 25% of packet loss, I feel like it should be possible to find a way even with just TCP. 
Even though idk if that could allow [state of the art](https://www.silver-peak.com/sites/default/files/infoctr/silver-peak_wp_measuringloss.pdf) detection.

**Comment by mirh** [comment]
QUIC also seems to offer quite a new level of insight into packet loss.

**Comment by mirh** [comment]
https://github.com/nielsbaloe/webrtc-php
https://github.com/cloudflare/speedtest/blob/main/src/engines/PacketLossEngine/PacketLossEngine.js

**Comment by flashlab** [comment]
hope it will become realized.
