### ISSUE TITLE
Add New Test Servers

### ISSUE THREAD

**Issue by diganto213** [librespeed/speedtest#353]
## Description
How to add new speedtest server other than the server found in the example html ? What are the free public server available ? If you have any idea on it ?

I would like add more server in different region like asia, africa, south america etc.

thank you

**Comment by adolfintel** [comment]
It's explained here: https://github.com/librespeed/speedtest/wiki/Multiple-test-points-(PHP)

You need to have some backends and add their URLs to the example, replacing my server.

Check out https://librespeed.org, it's our public instance with many servers.

**Comment by diganto213** [comment]
Thank you for your response.

So if I want to have my own destination server, I have to create it with the backends and point the example URL's to the destination server.

I want to have destination test server in Singapore, is there any free server available to server this purpose ?

Thank you

**Comment by adolfintel** [comment]
You have to host it yourself. If you can't, just use librespeed.org directly, we're constantly adding new servers.

**Comment by bhoeyong** [comment]
please add Asia server.....thanks

**Comment by Perflyst** [comment]
I am afraid but we don't have servers near Asia. If you can contribute one feel free to [submit](https://librespeed.org/submit/) it
