### ISSUE TITLE
Make test duration editable

### ISSUE THREAD

**Issue by dantebarba** [librespeed/speedtest#360]
## Description

Control speedtest measurement duration. For high speed connections it's too short.

## Why it should be implemented

In my case, the downstream starts slow but then bursts into higher numbers. Testing with aria2c I get faster results and I see the same bursting behavior. Would be great to have the ability to control the test duration. 

## Optional: implementation suggestions

Maybe as a startup command for the backend. 

My apologies if this has already been implemented.

**Comment by dantebarba** [comment]
Ignore, I've found the option to modify it.

**Comment by adolfintel** [comment]
For future reference, the settings are:
* time_dl_max
* time_ul_max
* time_auto
