### ISSUE TITLE
Upload speed incorrect sometimes

### ISSUE THREAD

**Issue by bpbp-boop** [librespeed/speedtest#361]
## Description
I'm seeing upload speeds being reported too high when the test is around 5000ms

## Server
PHP 7.4.7 
5.5.65-MariaDB MariaDB

## Client
Two examples with different browsers:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
1601420594137: IP: {"processedString":"x.x.x.x","rawIspInfo":""}, took 36ms
1601420595101: ping: 23.66 jitter: 219.17, took 964ms
1601420612305: dlTest: 2.02, took 14586ms
1601420621551: ulTest: 273.60, took 5200ms

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0
1601416944220: IP: {"processedString":"y.y.y.y.y","rawIspInfo":""}, took 41ms
1601416944797: ping: 40.00 jitter: 29.16, took 577ms
1601416954447: dlTest: 40.24, took 7039ms
1601416963510: ulTest: 592.16, took 5023ms

## Steps to reproduce
I can't reproduce easily

## Expected behaviour
Accurate upload :)

**Comment by adolfintel** [comment]
Could it be some QoS policy on the server? If it only happens after 5 seconds it could be

**Comment by adolfintel** [comment]
Can you do a screenshot of F12 > Network when this happens?

**Comment by bpbp-boop** [comment]
Thanks for the tip - I noticed some 413s when the upload section was happening. I've adjusted nginx's `client_max_body_size` and I'll monitor

**Comment by silvije2** [comment]
For me download speed makes no sense. Should I open a new issue?

https://librespeed.org/results/?id=0fejoes
https://librespeed.org/results/?id=0fegv9w

I am doing measurement from my laptop with firefox.
My network interface is gigabit ethernet.
Author states: No Flash, No Java, No Websocket, No Bullshit. - but results are impossible!
Protocol overhead should prevent you from getting even 1000Mbps on gigabit link as you can only measure goodput with javascript...
https://en.wikipedia.org/wiki/Goodput

lucky guessing measurement results?

**Comment by adolfintel** [comment]
Results are within margin of error for a gigabit connection, but if you host your test, you can disable overhead compensation by setting overheadCompensationFactor to 1.

**Comment by silvije2** [comment]
no, I am not hosting this, I just wanted to see what kind of results can I get on https://librespeed.org/ and if the results were accurate

funny thing nowhere on test page any words about margins of error - accuracy

luckyGuessingFactor sounds really good, thanks for your answer

**Comment by adolfintel** [comment]
There is no "official" margin of error, but I think +/- 10% is reasonable since it depends on a lot of factors that are out of our control.
