### ISSUE TITLE
Rasberry Pi 4 | Docker | Ubuntu

### ISSUE THREAD

**Issue by sdh91** [librespeed/speedtest#367]
Does not execute on Rasberry Pi 4 running Ubuntu 20 in docker via docker compose. Is this able to be ran on ARM? Docker executes but just reloads over and over. 

version: "3"

# LibreSpeedTest Docker compose attempt

services:
  speedtest:
    image: adolfintel/speedtest:latest
    environment:
      - TITLE=somesite SpeedTest
      - TELEMETRY=true
      - TZ=America/NewYork
      - PASSWORD=P@ssw0rd
    ports:
      - "x.x.x.x:8080:80"
    restart: unless-stopped

**Comment by adolfintel** [comment]
Unfortunately we know this, it doesn't work on ARM yet (#267)
The [go version](https://github.com/librespeed/speedtest-go) does work though

**Comment by sdh91** [comment]
Is there a docker for the go version?

**Comment by adolfintel** [comment]
@sdh91 Yes, you can create the container from the repo itself or download librespeed-go from docker hub.
