### ISSUE TITLE
extra data from input dont permit resend cos status != 0

### ISSUE THREAD

**Issue by mckaygerhard** [librespeed/speedtest#370]
i read documentation and try to parse extra data from an input text, **data is parsed good only in first try..** **but on each restart it raised an exception in log console**:
  "You cannot change the test settings after adding server or starting the test"

i used the singleserver gauges.. and put in startstop as si:

```
function startStop(){
....
extradata.exinput = I("text1").value;
if(s.getState()==-1){
s.setParameter("telemetry_extra",JSON.stringify(extradata));
}
....
	}else{
		//test is not running, begin
		I("startStopBtn").className="running";
		I("shareArea").style.display="none";
		I("ip").textContent="calculando...";
        s.setParameter("telemetry_extra",JSON.stringify(extradata));
		s.onupdate=function(data){
            uiData=data;
		};
....
```

**how can i get a extra data from an input text on each click on the start stop button?**

**Comment by adolfintel** [comment]
I did not expect anyone to need this. I'll implement it today

**Comment by mckaygerhard** [comment]
> I did not expect anyone to need this. I'll implement it today.
> 
> Update: done, you can now change the settings while in state 4

WOWOWOWO!!!! Thanks! puff well @adolfintel  i confess i modified the source of js before ask to you! to allow in state 3, but of course seems was not the correct state and in fact mu code was cacht parameter to allow change.. i see now was better to waith for you...

in fact i was thinking made an php with 3 blocks, first the form and a fake gui with controls and the button to push start/stop the test.. and when the user just push the button and event and a conditional in php with if/else that include the form as common part.. 

of course too complicated that idea.. thanks and keep the good work!

**Comment by adolfintel** [comment]
Yeah, state 3 is when the test is running, you really shouldn't change the settings in that state. State 4 is when the test is finished.
