### ISSUE TITLE
Telemetry Extra Field

### ISSUE THREAD

**Issue by bpalob** [librespeed/speedtest#374]
First of all, congratulations. This is really an amazing project. 

I do face a really simple challenge with the telemetry setup. I run 2 servers, 1 lan, 1 cloud. I´d like to get the results into the same DB. This works fine, all good. BUT I have a different behavior from CLI and App vs. Browser. 

CLI and APP post the server identification into the extra field. Browser Tests do not. So I wouldn´t know to which server a browser test has been made. I am sure this is a simpel configuration in the telemetry extra settings, but I just can´t get through to it. 

A hint is well appreciated. Thanks !
![Capture](https://user-images.githubusercontent.com/51025242/98601994-124d3300-22e0-11eb-922f-8ebf36efcf59.JPG)

**Comment by adolfintel** [comment]
Hi, can you give me a link to your test so I can check it?

**Comment by bpalob** [comment]
Hi Federico,

 

Wow, what a quick response. Thank you. I am sure it´s just me doing something stupid 😉

 

The 2 servers are running at:

 

http://192.250.236.223/

 

http://paca.mynetgear.com:1111/

 

Thanks !

 

KR, Bruno

**Comment by adolfintel** [comment]
I checked your page on http://paca.mynetgear.com:1111/ and there's nothing in the extra field because you're using the single server example. By default, that example doesn't put anything in there.

**Comment by bpalob** [comment]
Wow thanks, that´s a great hint. Will try to use the multi server version. There is some logic behind, I understand. Typically the frontend may be on a different server, having multiple backends,… not a standalone front/backend solution.

 

Thank you very much Federico.

**Comment by adolfintel** [comment]
No problem. Write me at info@fdossena.com if you need more help
