### ISSUE TITLE
Firefox slower than Chrome in LAN speed test

### ISSUE THREAD

**Issue by influx3k** [librespeed/speedtest#377]
## Description
I've noticed a weird issue with LibreSpeed and Firefox when testing on my LAN.  In Firefox on MacOS 10.14.6, I get much slower speeds than in Chrome on the same machine (2012 Mac mini).  Chrome maxes out my LAN bandwidth at ~988 Mbps (entire network is 1000 Mbps ethernet) but Firefox only achieves ~642 Mbps.  This was done on the same computer, just in the two different browsers and just a minute or so apart.  I also tried Firefox in Private Mode and got the same ~650 Mbps result.  I've done this repeatedly throughout the day and always get almost the same results; Firefox never gets over ~650 Mbps.

I also tried Firefox on an Ubuntu machine and get almost identical results as Chrome does on MacOS... ~985 Mbps.  So it seems like Firefox is Ok on Ubuntu, but slower for some reason on MacOS.

iperf on the same desktop machine to the Ubuntu server with LibreSpeed on it, results in ~940 Mbps.  Also tested to another Ubuntu server and got ~940 Mbps.

I would expect the two to be about the same in terms of raw throughput.  Does anyone know what might cause this and is there any way to fix it?  Is this an issue with Firefox?  Possible setting somewhere that isn't allowing enough connections to saturate all available bandwidth?

## Server
Ubuntu 20.10, LibreSpeed in Docker

## Client
Latest Chrome and Firefox

## Screenshots
![Screen Shot 2020-11-15 at 8 27 46 PM](https://user-images.githubusercontent.com/43835067/99318063-0825ba00-2835-11eb-8261-7442efe8bfd7.png)
![Screen Shot 2020-11-15 at 8 28 22 PM](https://user-images.githubusercontent.com/43835067/99318071-09ef7d80-2835-11eb-845f-3487e2b5f5ca.png)

**Comment by adolfintel** [comment]
Hi,
Do you see high CPU usage while running the test on firefox? Like one of the cores pegged at 100%

**Comment by influx3k** [comment]
Both cores go pretty high, like ~170% but don't fully max out.

**Comment by adolfintel** [comment]
Can you make sure that hardware acceleration is enabled in firefox?

**Comment by influx3k** [comment]
Where is that option? Under performance, "Use recommended settings" is checked; if you uncheck it, hardware acceleration is enabled.  So I'm assuming that it's on.

**Comment by adolfintel** [comment]
Try running a WebGL demo, like this one: https://webglsamples.org/aquarium/aquarium.html
If it runs smoothly, it's enabled.

**Comment by influx3k** [comment]
yeah it looks pretty smooth.  FF Advanced Prefs layers.acceleration.* all say disabled....

**Comment by adolfintel** [comment]
Does the problem still happen if you use the singleServer-basic example?

**Comment by influx3k** [comment]
What are you referring to exactly?

**Comment by adolfintel** [comment]
When you installed librespeed on your server, you used the singleServer-full example, which has fancy graphics.
Firefox puts rendering and javascript on the same thread, so if you use the basic example, which is just simple text, I'll be able to tell if it's the rendering or the test that's slowing down the browser.

**Comment by influx3k** [comment]
No idea.  I installed in Docker from a LinuxServer.io image.  Is there another Docker image that has the simple text graphics?

**Comment by adolfintel** [comment]
Oh ok, it's complicated then, nevermind.
My bet is that you're running into a CPU bottleneck because of rendering. If you have the time to do a non-docker install of librespeed on your server, we can confirm it using the basic example.

**Comment by influx3k** [comment]
I would definitely do it if there was a docker image available.  I'm sure others would find it useful too.

**Comment by influx3k** [comment]
Figured out how to change to the basic example/template.  Was pretty easy.  Shockingly, I got the same results in Firefox and it used the same amount of CPU.  Was like 270% CPU usage; both cores going almost max.  What gives?  What does that mean exactly?  Is this not a Firefox rendering issue then?

![Screen Shot 2020-11-18 at 8 18 40 PM](https://user-images.githubusercontent.com/43835067/99608418-d3079c00-29db-11eb-9fd7-188c645d62f8.png)

**Comment by adolfintel** [comment]
I was about to send you a container with the basic example for testing.

So it's a CPU bottleneck, I guess firefox on mac is heavier than on linux. This issue may be related https://support.mozilla.org/it/questions/1265464

Either way, glad to see it's not a librespeed bug

**Comment by ValZapod** [comment]
Well, you did not even try to check upload + download to saturate 2 gbit/s connection of Gigabite Ethernet.
