### ISSUE TITLE
no download test result

### ISSUE THREAD

**Issue by mzhboy** [librespeed/speedtest#378]
system: Ubuntu 20.04.1 on Pi4B
speedtest release 5.2.2

nginx and php configuration files [conf.zip](https://github.com/librespeed/speedtest/files/5587514/conf.zip)

What's wrong with my server settings?

![Snipaste_2020-11-24_12-21-06](https://user-images.githubusercontent.com/5281193/100048950-1a18e580-2e51-11eb-996a-09c73bb8e210.png)

**Comment by adolfintel** [comment]
You don't have OpenSSL installed, or its PHP module is disabled.

Also, please don't open issues for troubleshooting, use the troubleshooting thread or write me at info@fdossena.com

**Comment by mzhboy** [comment]
I'm sorry for misused github issue.
My problem has solved,  here post my solution just in case someone makes my mistake.

modification of configuration files

**file:/etc/nginx/sites-available/default**

        location ~ \.php$ {
                include snippets/fastcgi-php.conf; # forgot uncomment
        #
        #       # With php-fpm (or other unix sockets):
                fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
        #       # With php-cgi (or other tcp sockets):
        #       fastcgi_pass 127.0.0.1:9000;
                client_max_body_size 64M; # must > 20M for LibreSpeed
        }

**file:/etc/php/7.4/fpm/php.ini**

    post_max_size = 64M
    extension=openssl

----------------
must ensure nginx and php are working properly by using _info.php_
`<?php phpinfo() ?>`
