### ISSUE TITLE
Can't go past 1 Gbps

### ISSUE THREAD

**Issue by dlewis23** [librespeed/speedtest#379]
## Description
I recently got an internet upgrade to a better fiber setup with a SFP transceiver with a speed of 1.25 Gbps. But for some reason using this speed test I am unable to go past about 940 Mbps. I have 2 servers in datacenters close to me that are both have 10 Gig connections but can not pull faster then what the max of 1 gig ethernet can do, I can do iPerf tests between the 2 servers and get 9.4 Gbps. I know my connection is setup correctly because I can go to another speed test website and get 1244 Mbps download but using this test no matter what I do I can not go past about 940 Mbps. Is there something that I am missing that would cause this? 

## Server
Nginx 1.18.x with PHP 7.4.12

## Client
Safari, Chrome, Firefox on macOS.

**Comment by adolfintel** [comment]
As mentioned in the documentation, LS is not reliable above 1gbps, especially the JS version.

**Comment by dlewis23** [comment]
Didn't see that mentioned in the doc. Do you think this is something that will be resolved over time or would something like HTTP/2 or 3 help fix the issue?

**Comment by adolfintel** [comment]
It's mostly a CPU bottleneck on the client, it simply can't run javascript fast enough to measure fast connections reliably. I'm sure the situation will improve in the future, a high end PC can reach 6-7gbps easily.

The CLI version is not affected by this issue, unless your server is also slow, in which case I recommend using the Go backend
