### ISSUE TITLE
Better reverse proxy conf for go

### ISSUE THREAD

**Issue by toomuchio** [librespeed/speedtest#381]
I think it might be important to define a slightly more tuned nginx reverse proxy config in the wiki at https://github.com/librespeed/speedtest/wiki/Installation-(Go)#reverse-proxy-nginx-etc

Just to explain my changes using an upstream allows the caching of keepalive connections to the go backend which improves loading times.
SSL support and http2 support.
gzip off just so it doesn't interfere with the accuracy but it shouldn't compress the speedtest data by default anyway.
proxy redirect off - just more interference avoidance
proxy buffering off - is important that can make results inaccurate since nginx will attempt to buffer from the backend, this just makes it forward the requests as soon as the backend responds no buffering or delay.
client_max_body is just to ensure the upload test works off the bat, by default it wont unless you change this elsewhere.

```
upstream speedtest_backend {
    server 127.0.0.1:8989;
    keepalive 32;
}

server {
    listen 80;
    listen 443 ssl http2;
    server_name <SERVER NAME HERE>;

    ssl_certificate <SSL CERT HERE>;
    ssl_certificate_key <SSL KEY HERE>;

    location / {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Server $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        gzip off;
        proxy_redirect off;
        proxy_buffering off;
        client_max_body_size 256M;

        proxy_pass http://speedtest_backend/;
    }
}
```

**Comment by adolfintel** [comment]
That's very nice, thank you. I'll update the wiki later today

**Comment by adolfintel** [comment]
Updated :+1:
