### ISSUE TITLE
Automatic test with graphical output data

### ISSUE THREAD

**Issue by alfredonodo** [librespeed/speedtest#386]
Hi,
I think that librespeed is one of the best tool to measure Internet connection performance. It would be very useful to have the option to automate the test with several parameters (time interval, number of repetitions, min upload and download size, graphical output data sharing).
Thank you

**Comment by adolfintel** [comment]
You can make a script that does that using the command line version of LS: [https://github.com/librespeed/speedtest-cli](https://github.com/librespeed/speedtest-cli)

**Comment by alfredonodo** [comment]
Hi,
thank you for your fast reply, I know about command line version. I'm asking about similar to [this](https://testmy.net/auto).
