### ISSUE TITLE
results sharing image not shown 

### ISSUE THREAD

**Issue by dual-oo** [librespeed/speedtest#387]
Hello,

my browser displays a broken image icon.
Installed speedtest on a VPS **Ubuntu 20.04 | Nginx 1.19.6 | PHP 7.4 | PostgreSQL 12.5**

I found the Troubleshooting guide in wiki but cannot find a solution.

nginx conf:
```
server {
        listen 80;
        listen [::]:80;
        server_name speedtest.mydomain.tld www.speedtest.mydomain.tld;
        # enforce https
        return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name speedtest.mydomain.tld www.speedtest.mydomain.tld;
    include ssl/mydomain.tld;
    include global/header.conf;

    # your Speedtest installation
    root /var/www/speedtest;

    client_max_body_size 256M;
    gzip off;

    location ~ \.php$ {
        include fastcgi.conf;
        fastcgi_pass php-handler;
        fastcgi_param PHP_VALUE "
                upload_max_filesize = 256M
                post_max_size = 256M";
    }
}
```

`results/index.php` and `index.html` (example-singleServer-full.html) are the defaults.
The link is generated sucessfully and the stats.php is showing all recent results.

**Comment by adolfintel** [comment]
Make sure that the PHP FreeType2 and gd modules are installed and enabled in php.ini

**Comment by dual-oo** [comment]
I've installed freetype via `apt install freetype2-demos`

`php -i | grep -E "GD|FreeType"` shows:
```
GD Support => enabled
GD headers Version => 2.3.0
GD library Version => 2.3.0
FreeType Support => enabled
FreeType Linkage => with freetype
```
I think the freetype installation is not correct. Any advices?

**Comment by adolfintel** [comment]
I think the packages you have to install are called php7-gd and php7-freetype2
