### ISSUE TITLE
File Permissions

### ISSUE THREAD

**Issue by fr32k** [librespeed/speedtest#388]
## Description
File Permissions of Relevant Data Specify Who
/speedtest/backend/getIP_ipInfo_apikey.php
/speedtest/results/telemetry_settings.php
these contain sensitive information and should be chmod 660/600 

## Server - Webspace
it came to my attention because i installed it on a shared webspace

## Steps to reproduce
check out the current repository

## Expected behaviour
readable for each user

## Solution
Set files with security critical content as default
chmod 660 /speedtest/backend/getIP_ipInfo_apikey.php
chmod 660 /speedtest/results/telemetry_settings.php

**Comment by Perflyst** [comment]
git does not track permissions, only executable bits.

> it came to my attention because i installed it on a shared webspace

your webspace provider should protect your folder on the server with proper permissions, for example with 0750

**Comment by fr32k** [comment]
> git does not track permissions, only executable bits.
thank you for your explanation
