### ISSUE TITLE
[Feature request] Dark Mode

### ISSUE THREAD

**Issue by PoepiePeppie** [librespeed/speedtest#389]
## Description
Right now the website is just a plain white background, it would be nice to  have the option for a darkmode.

## Why it should be implemented
Relatively easy to implement. Easier on the eyes especially at night.

**Comment by SoufianeAbid** [comment]
use this library for dark mode 
https://darkmodejs.learn.uno/

**Comment by adolfintel** [comment]
This has been asked a lot of times already.
The included examples are just that, examples, they are there to show you how to make your custom UIs, there is no need to complicate them with multiple stylesheets or additional libraries.
