### ISSUE TITLE
has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by SoufianeAbid** [librespeed/speedtest#390]
hi there 

i have problem with backend result not showing and i see this message on console 

![github](https://user-images.githubusercontent.com/16512608/103568269-1b8af400-4e7a-11eb-8b52-fb67c655a1ad.png)

**Comment by adolfintel** [comment]
Contact me at info@fdossena.com and I'll help you troubleshoot it, it's probably just a PHP issue

**Comment by gkl1368** [comment]
I also has this problem.

**Comment by gkl1368** [comment]
> Contact me at [info@fdossena.com](mailto:info@fdossena.com) and I'll help you troubleshoot it, it's probably just a PHP issue
I also has this problem.

**Comment by adolfintel** [comment]
@gkl1368 send me an email with a link to your test if you can

**Comment by rizlas** [comment]
Any detailed info about this other than emails?
