### ISSUE TITLE
Custom Backend Issue

### ISSUE THREAD

**Issue by JoshBello** [librespeed/speedtest#392]
## Description
Trying to create a custom backend server but keep getting the same error as below. 

![Screenshot 2021-01-13 at 14 38 41](https://user-images.githubusercontent.com/45298642/104466344-09613200-55ad-11eb-8557-48b8c427662c.png)

## Command:
`librespeed-cli --local-json servers.json`

## Config:
```
servers.json
[
  {
    "id": 1,
    "name": "MMA Backend",
    "server": "http://joshbello.com/", 
    "dlURL": "garbage.php",
    "ulURL": "empty.php",
    "pingURL": "empty.php",
    "getIpURL": "getIP.php"
  },
  {
    "id": 1,
    "name": "MMA Backend",
    "server": "http://35.246.10.74/", # VM External IP
    "dlURL": "garbage.php",
    "ulURL": "empty.php",
    "pingURL": "empty.php",
    "getIpURL": "getIP.php"
  }
]
```

## Backend (GPC Hosted):

Here is the file hierarchy as suggested in the docs. 

![Screenshot 2021-01-13 at 14 37 04](https://user-images.githubusercontent.com/45298642/104466293-f8b0bc00-55ac-11eb-9a58-c4036e0b0d93.png)

I'm sure I'm missing something but not sure what.

**Comment by adolfintel** [comment]
@maddie Can you help him out?

**Comment by JoshBello** [comment]
So I managed to get it working using the CLI. I've now got LibreSpeed hosted on a VM (http://34.89.95.254/) but it won't detect my server. I have added the server like this:

```
var SPEEDTEST_SERVERS=[
	{	
		name: "GCP VM (London)",  //user friendly name for the server
		server: "//35.246.10.74/",  //URL to the server. // at the beginning will be replaced with http:// or https:// automatically
		dlURL: "garbage.php",   //path to download test on this server (garbage.php or replacement)
		ulURL: "empty.php",   //path to upload test on this server (empty.php or replacement)
		pingURL: "empty.php",   //path to ping/jitter test on this server (empty.php or replacement)
		getIpURL: "getIP.php"   //path to getIP on this server (getIP.php or replacement)
	},
```

Is there something I'm doing incorrectly?

**Comment by maddie** [comment]
It seems that you've got CLI working, and the URL you've posted seems to work. Have you got the problem sorted out?

**Comment by dnisbet** [comment]
Trying this also, not detecting the backend server. I can ping it, / displays <p>You don't have permission to access this resource.</p> but /getIP.php displays to correct JSON from the backend.

**Comment by dnisbet** [comment]
Ah nevermind, found the issue - not loading http elements behind https... :)
