### ISSUE TITLE
Speedtest results are wrong big time

### ISSUE THREAD

**Issue by paulpoco** [librespeed/speedtest#393]
## Description
A short description of what's going on
Speedtest results are wrong big time

## Server
Every info you can provide about your server: web server, database, PHP version, ... as well as server-side speedtest settings
If possible, provide an URL to your speedtest so we can check it

## Client
Browser, OS, type of connection, unusual software, ...
Docker Unraid
Have 150/150 service
![Screenshot_9](https://user-images.githubusercontent.com/801414/104657908-a76cff00-5676-11eb-9b73-b18ce134d49c.png)

## Steps to reproduce
* Do this
* Do that
* Bad stuff happens

## Expected behaviour
What should have happened

## Screenshots
If necessary, add screenshots of the test. 
F12 > Network screenshots can be particularly useful

**Comment by adolfintel** [comment]
Uhm, what's wrong exactly? You're testing over a local network, 1gbps seems perfectly normal

**Comment by paulpoco** [comment]
Should be testing the internet, not local lan.

**Comment by adolfintel** [comment]
It can only test the connection between you and the server, if you're on the same network, the connection doesn't go through the internet.

**Comment by luckydonald** [comment]
The other way is to run this as just a fronted to an existing server. See the MODE for that.
