### ISSUE TITLE
Can't access librespeed.org on safest setting.

### ISSUE THREAD

**Issue by klosteinmann** [librespeed/speedtest#394]
## Description
Can't access librespeed.org with Tor Browser on safest setting.

## Server
librespeed.org

## Client
Tor Browser 10.0.8
Windows 10 ameliorated (October 2020)
Ethernet

## Steps to reproduce
Enable safest mode on Tor Browser.
Run Security Level Safest
Type librespeed.org into adress/search bar

## Expected behaviour
What should have happened
Site should have loaded without JS and without bs.

## Screenshots
If necessary, add screenshots of the test. 

![image](https://user-images.githubusercontent.com/34807323/105635236-40afc880-5e62-11eb-8ea2-3647323d0782.png)
![image](https://user-images.githubusercontent.com/34807323/105635252-4c9b8a80-5e62-11eb-8ff2-18e15cf36848.png)
![image](https://user-images.githubusercontent.com/34807323/105635268-57561f80-5e62-11eb-8694-341584a7bea9.png)

F12 > Network screenshots can be particularly useful

## Additional information on extensions

![image](https://user-images.githubusercontent.com/34807323/105635291-66d56880-5e62-11eb-8a4c-91f2249e2a8b.png)

Sorry read no Java as no JavaScript. Even if you just measure the speed at the end of the tor nodes. Not the actual speed.

**Comment by adolfintel** [comment]
It can't work without JS, but I'll add a warning for users with JS disabled
