### ISSUE TITLE
Incorrect upload speed with nginx 1.19.6

### ISSUE THREAD

**Issue by s12321** [librespeed/speedtest#396]
There is extreme upload results from 2 different browsers in a intranet environment, which doesn't make any sense at all. 
Please see in attachment, Firefox it is over **800 Mbps** upload speed and in chrome, it is **0 Mbps** upload speed. I've tested  librespeed (current release) to host in apache2 and iis 8 with php7.3-fpm, the result is normal (upload speed and download about the same speed range).

anyone facing the same issue?

I've tried in nginx's host default.conf,  client_max_body_size 256M; but it doesn't help.

host info: nginx 1.19.6, php7.3-fpm, librespeed (current release)

Attached screen

![Screen Shot 2021-02-07 at 14 10 17](https://user-images.githubusercontent.com/12845065/107135584-0f4df700-6950-11eb-95dd-3ed64f75c102.png)
![Screen Shot 2021-02-07 at 14 09 12](https://user-images.githubusercontent.com/12845065/107135588-12e17e00-6950-11eb-9acd-dfdea9950e52.png)

**Comment by adolfintel** [comment]
Does this happen only with your server or also with the ones on librespeed.org?

**Comment by s12321** [comment]
Thanks :) 
it is only happen in my internal nginx server, librespeed.org speedtest is fine. 
not sure what i've missed from a standard setup.

**Comment by adolfintel** [comment]
I'm not sure because I don't use nginx myself. It's possible that when it sees an incoming request of that size it immediately responds with an error and stops the upload. Maybe firefox doesn't add that header to the request.

**Comment by navidmafi** [comment]
i have this problem too
Chrome ping and jitter is far different than Firefox ping and jitter
using LiteSpeed with Unix (shared hosting)

**Comment by unbekannt3DE** [comment]
Try disabling HTTP/2 for that vhost if enabled, Cloudflare had a blogpost about it few months back: https://blog.cloudflare.com/delivering-http-2-upload-speed-improvements/

**Comment by RaphiMC** [comment]
I have the same problem. The upload speed is completely wrong when using the speedtest on Nginx. I tried the same thing on Apache2 and everything worked there.

Server information
* PHP 7.3
* NGINX 1.14.2
* OS: Debian 10

![grafik](https://user-images.githubusercontent.com/50594595/109794343-0d591a00-7c16-11eb-8433-a48c5c4e3ab2.png)

**Comment by s12321** [comment]
> Try disabling HTTP/2 for that vhost if enabled, Cloudflare had a blogpost about it few months back: https://blog.cloudflare.com/delivering-http-2-upload-speed-improvements/

I've test with http/2 (https) and without http/2 (https) on apache and nginx, yes, I think this is the key factor to cause this issue.

**Comment by s12321** [comment]
@RaphiMC add client_max_body_size 20M; or more M into nginx.conf  in order to fix this issue. 
@unbekannt3DE both of apache2 and nginx 1.9.x both are working fine under http2

**Comment by amanjuman** [comment]
> 
> 
> I have the same problem. The upload speed is completely wrong when using the speedtest on Nginx. I tried the same thing on Apache2 and everything worked there.
> 
> What I tried: Editing nginx.conf and set client_max_body_size to 200M. I also edited the php.ini and changed the post upload size to 200M
> 
> Server information
> 
>     * PHP 7.3
> 
>     * NGINX 1.14.2
> 
>     * OS: Debian 10
> 
> 
> ![grafik](https://user-images.githubusercontent.com/50594595/109794343-0d591a00-7c16-11eb-8433-a48c5c4e3ab2.png)

Can you provide me your Nginx config for librespeed?

**Comment by Perflyst** [comment]
The only "special" configuration for the servers on librespeed.org is `client_max_body_size 21M;`. It should work fine if this option is added to the vHost.

**Comment by brujoand** [comment]
Setting `client_max_body_size 21M;` brought my reported upload speed down from 2543Mbps to a more reasonable 215Mbps. `nginx.ingress.kubernetes.io/proxy-body-size: "21m"` for those on nginx-ingress in kubernetes.

**Comment by Perflyst** [comment]
If the problem still exists please let us. We will re-open this issue
