### ISSUE TITLE
timestamp does not show the correct time from the server

### ISSUE THREAD

**Issue by KRIPT4** [librespeed/speedtest#398]
## Description
The time zone is not correct, timestamp shows a UTC time zone and does not take the server's time zone (GTM-3). The server is configured with a GTM-3 NTP.

## Server
Ubuntu 18.04.5 LTS (bionic) in VirtualBox 6.1, Windows 10 Pro 20H2 19042.746

## Client
Chrome Version 88.0.4324.104 (Build oficial) (64 bits) - Windows 10 Pro 20H2 19042.746
Opera LVL2 (core: 72.0.3815.487) (64 bits) - Windows 10 Pro 20H2 19042.746
Chrome Version 88.0.4324.152 - Android 10 - Mi A2

## Steps to reproduce
* Install https://fdossena.com/?p=speedtest/quickstart_v5_ubuntu.frag
* terminal > timedatectl
* terminal > timedatectl list-timezones | grep -i Argentina
* terminal > timedatectl set-timezone America/Argentina/Buenos_Aires
* terminal > sudo timedatectl set-ntp no
* terminal > sudo apt-get install ntp
* terminal > sudo nano /etc/ntp.conf add servers https://www.pool.ntp.org/zone/ar
* terminal > sudo service ntp reload

## Expected behaviour
timestamp should show the correct time zone.

## Screenshots

Terminal > timedatectl
Local time: Tue 2021-02-09 15:12:43 -03
Universal time: Tue 2021-02-09 18:12:43 UTC
RTC time: Tue 2021-02-09 18:12:44 UTC
Time Zone: Ameria/Argentina/Buenos_Aires (-03, -0300)
System clock synchronized: Yes

Image timestamp > 2021-02-09 18:12:43

**Comment by adolfintel** [comment]
It's supposed to use the timezone of the database server. Can you check that mariadb is using the correct timezone?

Related post on stackoverflow: https://stackoverflow.com/questions/930900/how-do-i-set-the-time-zone-of-mysql

**Comment by AntiThesi** [comment]
Hey, are you the guy who worked on captain claw - unity?
