### ISSUE TITLE
GetIP.php Error 500 with php8.0-fpm

### ISSUE THREAD

**Issue by mildis** [librespeed/speedtest#403]
## Description
getIP.php fails with error 500

## Server
debian 10 with php8

## Screenshots
`<br /> <b>Fatal error</b>: Uncaught TypeError: fwrite(): Argument #1 ($stream) must be of type resource, bool given in /var/www/speedtest-5.2.2/backend/getIP.php:117 Stack trace: #0 /var/www/speedtest-5.2.2/backend/getIP.php(117): fwrite() #1 {main} thrown in <b>/var/www/speedtest-5.2.2/backend/getIP.php</b> on line <b>117</b><br />`

**Comment by adolfintel** [comment]
Did you give your web server user (like www-data) write access to the backend folder?

**Comment by mildis** [comment]
Yeap it has.
`getIP_serverLocation.php` did not exists, so `fopen()` returned `false` instead of a resource and it looks like php8 seems a bit more picky about TypeError.
As soon as I created and populated `getIP_serverLocation.php`, the error disappeared.
`$locFile` is being `fopen`ed even if it does not exist.

**Comment by adolfintel** [comment]
Can you check if the error is still present in the current master branch? getIP.php has been revamped by a PR.

**Comment by mildis** [comment]
Seems OK even after renaming `getIP_serverLocation.php` so it won't find it.

**Comment by adolfintel** [comment]
Yeah, the new version doesn't use fopen and fwrite anymore. I'll make a new minor release tomorrow with all the changes since september
