### ISSUE TITLE
Speedtest reports null value for UL test, but it seems the UL test does not start properly

### ISSUE THREAD

**Issue by scrisafulli-ita** [librespeed/speedtest#404]
Hi Federico,
I have observed that sometimes the speedtest reports null value for UL tests.
It seems like the UL test does not start (I have also checked the log and these tests were not manually aborted).
Did you ever notice this behaviour? Is there a way to check if the test does not start as it seems or if it starts and measure 0?

**Comment by adolfintel** [comment]
Sorry for the late reply, I didn't see the issue yesterday.
Do you see errors during the upload test? Either in the console, the log, or the network tab?
