### ISSUE TITLE
errors when changing telemetry_settings.php in entrypoint.sh

### ISSUE THREAD

**Issue by bes1967** [librespeed/speedtest#406]
Hi
First of all - thank you for this software. 
But after the last update, results/stats.php always shows a warning about the need to specify a password in telemetry_settings.php. 
This is due to the fact that in entropoint.sh the command:
sed -i s/\$Sqlite_db_file\ =\ \".*\"/\$Sqlite_db_file=\"\\\/database\\\/db.sql\"/g /var/www/html/results/telemetry_settings.php
is used to change telemetry_settings.php.
and in the file itself the value:
$stats_password = 'PASSWORD';
is indicated.
Due to the difference in spaces and quotes, no change occurs. The same goes for other variables in telemetry_settings.php.
After I changed my telemetry_settings.php (just edit to $stats_password="PASSWORD"; - for example), everything worked.
It would be nice to fix this little bug
thank you.
Update: I'm using Docker image. By the way, same error on $db_type and $enable_id_obfuscation. But handling$Sqlite_db_file  is ok.

**Comment by adolfintel** [comment]
Yeah, I'm stupid and forgot to change the regexes in entrypoint.sh
Should be fixed now.
