### ISSUE TITLE
Downstream cannot be tested

### ISSUE THREAD

**Issue by scaarup** [librespeed/speedtest#409]
## Descriptio: 
Downstream cannot be tested and the js console reports an error
![image](https://user-images.githubusercontent.com/8055470/109392953-6b88b300-791f-11eb-914d-be3144d5b18b.png)

## Server
Docker container from https://hub.docker.com/r/linuxserver/librespeed

## Client
Latest Chrome on Ubuntu and Mac OS.

## Steps to reproduce
* pop the page and press test

## Expected behaviour
I expect downstream to be tested as well

**Comment by adolfintel** [comment]
I'll say this for both this issue and #408.
**That is not the official docker image of librespeed, the official image is adolfintel/speedtest**, whoever built linuxserver/librespeed must have fucked something up.

**Comment by scaarup** [comment]
Thank you very much, that resolved the issue.

On your wiki you say "A docker version of LibreSpeed is available on docker hub: https://hub.docker.com/r/adolfintel/speedtest/". This does not imply "official" in any way - the link at dockerhub doesn't even contain the word "librespeed".

**Comment by adolfintel** [comment]
I know, it's just that the project used to be called adolfintel/speedtest on github as well, before it became librespeed and I didn't want to break a bunch of installs by changing it on docker.
