### ISSUE TITLE
cant see result image

### ISSUE THREAD

**Issue by nishith-p-shetty** [librespeed/speedtest#411]
## Description
A short description of what's going on

## Server
Every info you can provide about your server: web server, database, PHP version, ... as well as server-side speedtest settings
If possible, provide an URL to your speedtest so we can check it

## Client
Browser, OS, type of connection, unusual software, ...

## Steps to reproduce
* Do this
* Do that
* Bad stuff happens

## Expected behaviour
What should have happened

## Screenshots
If necessary, add screenshots of the test. 
F12 > Network screenshots can be particularly useful

**Comment by nishith-p-shetty** [comment]
i am not getting the result image after the test is completed.
and if i use the result link i got it shows blank white page
example-singelServers-full.html
<img src="" id="resultsImg" /> i found this in the html file img source is empty....??

**Comment by adolfintel** [comment]
Make sure you have the php gd and freetype2 modules installed and enabled

**Comment by nishith-p-shetty** [comment]
> Make sure you have the php gd and freetype2 modules installed and enabled

I am hosting it on windows 10 xampp
everything is fine all works asowme u have made a asowme work
but I don't get a image after test is completed
if I
![Screenshot (119)](https://user-images.githubusercontent.com/69454628/109425749-e16c4780-7a0f-11eb-802b-6e07e5478b38.png)
 use link it shows blank white page

**Comment by nishith-p-shetty** [comment]
thanks a lottttt i enabled gd it wotked thanksssssss veryyyy veryyy much
