### ISSUE TITLE
Less CPU intensive garbage generation

### ISSUE THREAD

**Issue by ms-jpq** [librespeed/speedtest#412]
## Description

I am running LIbrespeed under Docker on a Raspberry Pi 4B. This is of course not a very fast device, but it is still very capable.

I noticed that on a LAN speedtest, the download is dramatically slower than the upload, and when I checked CPU usage, it seems like the garbage generation process is maxing out the CPU.

You can see in the screenshots below that the pattern is that when I am downloading, I max out the CPU at 100% and when im uploading, I am only using about 50% CPU. 

## Why it should be implemented

The most likely culprit of the slowness is due to `openssl_random_pseudo_bytes` in `garbage.php`. If we swapped this one out for a faster garbage gen, people who have lower end devices will be able to use Librespeed as well.

## Optional: screenshots

![图片](https://user-images.githubusercontent.com/50598611/109786750-567f7e80-7bc2-11eb-8ef0-0f6c2a6e6c94.png)

![图片](https://user-images.githubusercontent.com/50598611/109786852-78790100-7bc2-11eb-94aa-15bbc9e76526.png)

**Comment by adolfintel** [comment]
Actually openssl_random_pseudo_bytes is only called once for each stream, it's used to generate a megabyte of garbage data that's repeated for that stream (up to 100 times in the current implementation).
If your machine is too slow for this, a possible solution suggested in the documentation would be to use a large incompressible file, like a video. Let me know if that helps.

**Comment by ms-jpq** [comment]
Looks like I read your code wrong sorry. was late at night

**Comment by adolfintel** [comment]
It's ok, it's a perfectly valid point, there should be an easier way to change this in the docker version.
