### ISSUE TITLE
Wiki update: CentOS 8 Stream installation

### ISSUE THREAD

**Issue by cbrookins** [librespeed/speedtest#422]
This was my setup for a CentOS stream build.

```
sudo dnf install https php git
git clone https://github.com/librespeed/speedtest
cd speedtest
sudo cp -R backend example-singleServer-pretty.html *.js /var/www/html
cd /var/www/html
sudo mv example-singleServer-pretty.html index.html
sudo chown -R apache *

sudo firewall-cmd --permanent --add-service=http
sudo firewall-cmd --reload
```

**Comment by adolfintel** [comment]
Thanks for the commands.
Can you check that the telemetry and results sharing feature is working on CentOS? It would be helpful

**Comment by cbrookins** [comment]
I tried the sqlite setup with no success.  I haven't had the need to use those features so I am not too familiar with their setup.  Wiki on those features seems pretty straight forward though so I am not sure where I messed up.  I can give it another go.
