### ISSUE TITLE
librespeed.org add server ?

### ISSUE THREAD

**Issue by kepon85** [librespeed/speedtest#423]
Hello,

If you wan't to add instance to librespeed.org i propos my instance : https://speedtest.retzo.net/

City: | Falkenstein
Country: | Germany
Hoster : hetzner

Thank's for this work !
David

**Comment by adolfintel** [comment]
Thanks David, we'll test it and add it asap

**Comment by Perflyst** [comment]
Would be nice if you can add IPv6 too. It probably is already configured on your server but only missing in your DNS and/or apache vhost.

**Comment by kepon85** [comment]
> Would be nice if you can add IPv6 too. It probably is already configured on your server but only missing in your DNS and/or apache vhost.

It's being DNS propagated ... Thanks!

**Comment by Perflyst** [comment]
There is an AAAA record now but the A record is gone :thinking:

**Comment by adolfintel** [comment]
@kepon85 done, let me know if you want to have it reenabled
