### ISSUE TITLE
Required php submodules

### ISSUE THREAD

**Issue by driesmp** [librespeed/speedtest#426]
Can you share / document what are the required php module dependencies?

https://github.com/librespeed/speedtest/wiki/Installation-(PHP) is this still correct?
Only mentions OpenSSL submodule and FreeType 2 for results sharing and respective database module for that database.

Question is comming from an downstream bug report on FreeBSD, my port might not have the necessary modules defined right now:

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=256891

**Comment by adolfintel** [comment]
As far as I know you need the OpenSSL module for the garbage data generation, FreeType2 for the sharable image, json (which is usually preinstalled with PHP), mysql/postgre/sqlite and the respective PDO module depending on the chosen database. It shouldn't require anything else as far as I know.
