### ISSUE TITLE
How many connections

### ISSUE THREAD

**Issue by asharma2040** [librespeed/speedtest#428]
Hi,
First of all thanks a lot for this great package
I dont have a issue but a simple question.
How many devices can do a speedtest at the same time? Is it dependent on server size where the speedtest is installed? If yes, how many devices can do a speedtest at once on a 2 gig ram machine.

Thanks!

**Comment by adolfintel** [comment]
It mostly depends on the bandwidth available to the server. If you have 1gbps and you're tesing 20mbps connections, you can do several tests at the same time, but if you're testing a 1gbps connection, you only have enough bandwith for one.
The server side code is pretty fast so CPU and RAM won't affect this unless you're using something really underpowered. The go backend is even lighter.
