### ISSUE TITLE
CLI Interface

### ISSUE THREAD

**Issue by HuaweiDonor** [librespeed/speedtest#429]
Feature request

Make cli interface, use on non-gui system

curl https://librespeed.local/

Output

DW: XXX Mb/s
UP:  XXX Mb/s

**Comment by Perflyst** [comment]
I guess you are looking for https://github.com/librespeed/speedtest-cli

**Comment by adolfintel** [comment]
Yeah, we already have it. You can find prebuilt binaries in the releases section
