### ISSUE TITLE
Hope that there are parameters that can increase the speed measurement time or speed measurement flow

### ISSUE THREAD

**Issue by zoumeng** [librespeed/speedtest#430]
## Description
A short description of your idea

The wifi speed will fluctuate, hope to have a longer time for speed measurement. Are there any parameters that can modify the speed test time or speed test flow rate.

## Why it should be implemented
Who it would benefit, ...

## Optional: implementation suggestions
If you have experience in this field, feel free to give us suggestions

## Optional: screenshots
Add some screenshots, mockups, ... if they help clarify what you want

**Comment by adolfintel** [comment]
There is, see here: https://github.com/librespeed/speedtest/wiki/Making-a-custom-front-end#test-parameters

Set `time_auto` to `false` and `time_ul_max`, `time_dl_max` to the duration that you want in seconds
