### ISSUE TITLE
Docker container won't start with existing files in /var/www/html

### ISSUE THREAD

**Issue by derekpovah** [librespeed/speedtest#450]
## Description
The container fails to start if there are existing files in `/var/www/html`

## Steps to reproduce
* Start the container with a Docker volume that drops a file in `/var/www/html`
  * `docker run -d -v /path/to/file:/var/www/html/some-file.txt adolfintel/speedtest`

## Expected behaviour
The container should start

## Additional Details
As of this writing, `/var/www/html` in the parent image (`php:7.2-apache`) is empty, so what's the benefit of doing this?:
https://github.com/librespeed/speedtest/blob/eca7f06e217b739e2c6cb14f3f4b4da9ea9be921/docker/entrypoint.sh#L6-L7

**Comment by sstidl** [comment]
Please elaborate on the use-case you are trying to achive.

**Comment by sstidl** [comment]
the /var/www/html directory is not intended to be overmounted. use the /speedtest directories instead. look into entrypoint.sh to understand how this is working
