### ISSUE TITLE
Speedtest backend in Prague

### ISSUE THREAD

**Issue by melnijir** [librespeed/speedtest#462]
There is another librespeed instance available:

https://speedtest.cesnet.cz

frontend is just a slightly modified, but backend is exactly the same, so it could be used by speedtest-cli:

```
[
  {
    "id": <ID>,
    "name": "Prague, Czech Republic (CESNET)",
    "server": "//speedtest.cesnet.cz/backend/",
    "dlURL": "garbage.php",
    "ulURL": "empty.php",
    "pingURL": "empty.php",
    "getIpURL": "getIP.php",
    "sponsorName": "CESNET",
    "sponsorURL": "https://www.cesnet.cz"
  }
]
```

server is connected via 10Gbps link and should be stable and online for a long time (current uptime is more than 1 year).

**Comment by adolfintel** [comment]
I know this site but unless you're the owner I can't just add it to our public servers without their consent.

**Comment by adolfintel** [comment]
Alright, do you mind sending me an email from that domain just to be 100% sure?
info@librespeed.org

**Comment by melnijir** [comment]
Sure, no problem. :)

**Comment by adolfintel** [comment]
Added it, thanks!

**Comment by melnijir** [comment]
Thank you for all the effort you put into this great project!
