### ISSUE TITLE
inaccurate upload speed test

### ISSUE THREAD

**Issue by Mlocik97** [librespeed/speedtest#464]
## Description
I opened librespeed.org and clicked on "measure speed", I got this result
https://librespeed.org/results/?id=1th5qwr

## Server
librespeed.org

## Client
Chrome 97.0.4692.99, Ubuntu 20.04

I have ADSL 12/0.6Mbps, realspeed of upload is around ~0.6Mbps I got result 2.16Mbps 

## Expected behaviour
What should have happened

## Screenshots
![Snímka obrazovky z 2022-01-30 17-45-51](https://user-images.githubusercontent.com/34808350/151708779-b2f37685-e323-4ce0-a662-d331c0606d13.png)

**Comment by adolfintel** [comment]
Are you using some kind of proxy or VPN software?

**Comment by Mlocik97** [comment]
no, there isn't any VPN or proxy.

**Comment by adolfintel** [comment]
Does this happen with all servers or only this one?

**Comment by Mlocik97** [comment]
https://librespeed.org/results/?id=0tnwubf


seems like just that one server.

**Comment by adolfintel** [comment]
It works for me, but maybe @melnijir wants to take a look at it since it's his server

**Comment by melnijir** [comment]
I've just checked it and the CORS seems to be set correctly:

```
Access-Control-Allow-Headers: Content-Encoding, Content-Type
Access-Control-Allow-Methods: GET, POST
Access-Control-Allow-Origin: *
```

Also if you look into the log, there are CORS problems on pl1.backend.librespeed.org as well. Seems more like a problem on the client side to me.
