### ISSUE TITLE
New server in Iran

### ISSUE THREAD

**Issue by BardiaMGTGC** [librespeed/speedtest#468]
Hey
I'm submitting another one in Tehran today.
https://st.bardia.tech/
You can access everything here and add it to the server list.
My contact email is fakeshell@bardia.tech
Its hosted and sponsored by Bardia Moshiri. (https://bardia.tech/)
ISP/Datacenter is Faraso

Also for a server that i host in Qom
I did a typo in my github issue 
The name should be corrected from Ghom to Qom
Thanks.

**Comment by adolfintel** [comment]
Thanks for the server. You seem to have a problem with getIP.php, make sure it's allowed to connect to ipinfo io

**Comment by BardiaMGTGC** [comment]
Hello
as discussed here: https://github.com/librespeed/speedtest/issues/444
This happens because of sanctions in Iran
There isn't anything i can do about it.
Sorry

**Comment by BardiaMGTGC** [comment]
any updates?

**Comment by adolfintel** [comment]
Sorry for the delay, I didn't see your reply last week. I've added your server now, thanks!
