### ISSUE TITLE
PHP version

### ISSUE THREAD

**Issue by mathisono** [librespeed/speedtest#469]
URL : xxxx (7.4.20 under
X-Powered-By: PHP/7.4.20)
 Installed version : 7.4.20
 Fixed version : 7.4.28
  Plugin Description:
The version of PHP installed on the remote host is prior to 7.4.28. It is,
therefore, affected by a vulnerability as referenced in the Version 7.4.28
advisory.
 Note that Nessus has not tested for this issue but has instead relied only on
the application's self-reported version number.
 Host Scan End: 2022-02-24 05:49:45 -0800

**Comment by adolfintel** [comment]
Should be already fixed, see #467
![image](https://user-images.githubusercontent.com/16307689/155785456-5f58d843-5bc7-4ccc-b508-6837dcbb5752.png)
