### ISSUE TITLE
Upload Result is slow

### ISSUE THREAD

**Issue by dateno1** [librespeed/speedtest#470]
## Description
Other result is OK but upload is very slow

## Server
OS : Ubuntu 18.04 with 5.15.6 x64
nginx 1.20.1 + php : 7.4.28/FPM + without SQL
librespeed is lastest (Updated today) (use 'example-singleServer-pretty.html'/All Setting is default)

NGINX has no size limit
PHP Upload limit ; 512M/Post limit : 2G

Network : 500/500M, Fiber

Speedtest.net result is OK (Up/Down 350~450Mbps)

## Client
Windows 10 x64
Chrome/Firefox Lastesst
Network : 500/500M, Fiber

## Steps to reproduce
Running Test

Test on another Internet line + computer but same result

You can check on https://speed.dateno1.com

## Screenshots
![Up_Speed](https://user-images.githubusercontent.com/12645246/156708992-dc557278-8e08-48c0-be15-e254f7feec94.png)

**Comment by Computroniks** [comment]
You say that your network speed is 500/500, is that the servers speed or your speed?

**Comment by dateno1** [comment]
> You say that your network speed is 500/500, is that the servers speed or your speed?

Server&Client using both 500Mbps Fiber.

**Comment by Computroniks** [comment]
Hmm, have you tried testing with a different service such as Speedtest.net?

**Comment by dateno1** [comment]
> Hmm, have you tried testing with a different service such as Speedtest.net?

Other service test result is OK (Tested on client/server both side)

I think it seem failed to upload dummy data for test on browser

**Comment by Computroniks** [comment]
Ok, I will have a look on my system tonight. In the meantime, could you possibly send a screenshot of the network panel of devtools with the name column expanded so I can see the full request.

**Comment by Computroniks** [comment]
Ok, I will have a look on my system tonight. In the meantime, could you possibly send a screenshot of the network panel of devtools with the name column expanded so I can see the full request.

**Comment by dateno1** [comment]
> Ok, I will have a look on my system tonight. In the meantime, could you possibly send a screenshot of the network panel of devtools with the name column expanded so I can see the full request.

How can i expand 'name column'?

**Comment by dateno1** [comment]
> If you hover over the line between the name and status columns and then click and hold, you should be able to resize the column.

OK I understand what do you want

I will upload screenshort later

**Comment by dateno1** [comment]
![DevTools](https://user-images.githubusercontent.com/12645246/161880893-65ae04a2-33ea-45d1-8898-25a8ae7a8076.png)
DevTools

![Speedtest net Server](https://user-images.githubusercontent.com/12645246/161880935-954953d3-cbcc-4272-9ddf-a7892f14e8b2.png)
Server
![Speedtest net Client](https://user-images.githubusercontent.com/12645246/161880969-2f5b75b7-a938-437b-aa19-6b4656d7b5f5.png)
Client

**Comment by Computroniks** [comment]
Hmm, this seems a bit odd. I get the same cancelled requests as part of the upload test. It might be worth checking out #161 for more details on troubleshooting help

**Comment by dateno1** [comment]
> Hmm, this seems a bit odd. I get the same cancelled requests as part of the upload test. It might be worth checking out #161 for more details on troubleshooting help

Already double checked 'general troble shooting'&'ReadMe' before Create server

What i neeed to do?

**Comment by Computroniks** [comment]
The other suggestion in #161 was to email @adolfintel on [info@fdossena.com](mailto:info@fdossena.com) but be aware they might take a while to respond as they seem quite busy.

**Comment by jsravn** [comment]
I see the same thing. 1000/110 connection, but upload is always limited to about 20mbps (to a server with 1Gbps link). Other sites all work fine and show my correct dl/ul.

**Comment by seb81** [comment]
it might be because of http2

**Comment by dateno1** [comment]
> it might be because of http2

Thanks for help.

Work Well.
