### ISSUE TITLE
Raw IP:port as server url for SPEEDTEST_SERVERS variable

### ISSUE THREAD

**Issue by joeblowout** [librespeed/speedtest#471]
## Description
raw ip in digits x.x.x.x:port in addition to domain name

## Why it should be implemented
for multiple test points, each server has to have domain its own domain name pointed towards backend program, raw ip with port won't work atm, which I find it a little tiring to bind every server with domain name, thank you, please consider.

**Comment by SubMGRru** [comment]
you can use the domain too, don't forget to specify the protocol, for example:

http://127.0.0.1:67/

do not use httpS for connections with IP

**Comment by joeblowout** [comment]
ah, my frontend uses https, no wonder, thx for pointing out
