### ISSUE TITLE
[Docker] Speedtest "hangs" a minute in getIP.php before measurement starts

### ISSUE THREAD

**Issue by jacotec** [librespeed/speedtest#474]
## Description
I'm running a speedtest in my homelab to measure throughput from internal clients and connectivity from the outside. Speedtest runs as the official docker image.

I find quite often that, after pressing the "Start" button, the button turns red but nothing happens for a long time. Finally the measurement starts.

## Server
Official docker image adolfintel/speedtest running on an ESXi VM @ Dell R720

## Client
Edge, Chrome @ Win10, Safari @ IOS etc.

## Steps to reproduce
* Open the speedtest webpage
* Click on "Start"
* The button turns red and nothing happens
* After around 1 minute the measurement starts properly, showing good results

## Expected behaviour
The measurement should start immediately after pressing "Start"

## Screenshots
I found that in this case it hangs in "getIP.php", see below:

![image](https://user-images.githubusercontent.com/3321655/158813403-f42aa3bd-e4a6-462b-8ca6-6a59074b6d41.png)

However, the IP address is correctly shown (but with ISP "Unknown").

**Comment by adolfintel** [comment]
This happens if your server is unable to contact ipinfo.io to get the ISP information.
You can either allow it to do so or just disable ISP detection (see here: https://github.com/librespeed/speedtest/wiki/Making-a-custom-front-end, look for getIp_ispInfo)

**Comment by jacotec** [comment]
@adolfintel Thanks, you are correct :-)

My IDS did not like the query and had blocked the host:

![image](https://user-images.githubusercontent.com/3321655/158816547-cd4a7029-320f-46fa-9af9-b89fe3a752aa.png)

Maybe it would be a good improvement to lower the timeout waiting for the result from ipinfo.io in general? A full minute is quite long, 5 seconds might do it. Or start the query in parallel to the speed test procedure - and if the result is not there when the speedtest finishes, display "unknown".

Just imagine ipinfo.io is down and every instance speedtest on that planet has this issue.

**Comment by adolfintel** [comment]
I agree, I'll see if I can control it. It's probably just the default timeout for TCP sockets, if the connection is dropped without returning an RST or something to the client, the system cannot know that the connection was blocked, it could just be a slow server.
