### ISSUE TITLE
[Feature Request] Option for MBps v Mbps

### ISSUE THREAD

**Issue by raviwarrier** [librespeed/speedtest#475]
## Description
It would be nice if there was a toggle for showing results in MBs v Mbs. Or if not a toggle, then just show both results like 100 Mbps (12.5MBps). It's just for us noobs who are more comfortable with MBs instead of Mbs.

## Why it should be implemented
Everyone

## Optional: implementation suggestions
If you have experience in this field, feel free to give us suggestions

## Optional: screenshots
Add some screenshots, mockups, ... if they help clarify what you want

**Comment by Computroniks** [comment]
Whilst this wouldn't be too hard to implement I don't think (just divide the output by 8) I am not sure if it is really necessary as internet speed is almost always measured in bits per second and is sold in bits per second. Therefore I would think that it could lead to some confusion if a user is expecting their results in bits per second but the server owner has decided to use bytes. As for why bits are used, it seems to just be a left over from some of the very early networks. Here is a Reddit post offering a bit more explanation https://www.reddit.com/r/explainlikeimfive/comments/1at0fr/comment/c90jcuc/

**Comment by raviwarrier** [comment]
I understand and for most techies it's not a problem. But I have people on my network who aren't (like my mother and my friends) and it's just better for them to see than to remind them of "divide it by 8" every time. It's not a big problem, but just adds towards the overall usability and includes the non-techies into the fold. Just a "nice-to-have" feature.

**Comment by raviwarrier** [comment]
Okay. Closing the request. Cheers. And BTW, if you are the dev (or part of the dev team), good job mate! :) Have a good one.

**Comment by Computroniks** [comment]
Not part of the dev team just use the service. But I have to agree with you, well done to them!
