### ISSUE TITLE
"No servers available" - https://librespeed.org/backend-servers/servers.php not resolving

### ISSUE THREAD

**Issue by initd0** [librespeed/speedtest#482]
When trying to do a speedtest, it constantly says "No servers available", after searching for 2min.

https://librespeed.org/backend-servers/servers.php is also not resolving. ive tried from different country IP addresses.

Is there something happening on your end?

**Comment by IndiDaFunk** [comment]
same here speed test are failing

**Comment by adolfintel** [comment]
A process on the frontend server has crashed, we'll fix it soon
