### ISSUE TITLE
bit/s and byte/s

### ISSUE THREAD

**Issue by Yasmanyfs** [librespeed/speedtest#483]
Please add support for bit/s and byte/s choose button, also choose how many multistream used for each test. Database option without docker.

**Comment by Computroniks** [comment]
The bit/s and byte/s part of this request is a duplicate of #475

**Comment by Yasmanyfs** [comment]
#475 sorry it was not showing to me. I understand the reason why the developer not included this feature. And about database I miss that part of configuration, I Wil check out that.
