### ISSUE TITLE
Security issue: Update base Docker image layer to the latest version of PHP

### ISSUE THREAD

**Issue by disc** [librespeed/speedtest#496]
## Description
The current docker image [adolfintel/speedtest](https://hub.docker.com/r/adolfintel/speedtest) uses php 7.4.28 that contains a few security issues:
https://bugs.php.net/bug.php?id=81719
https://bugs.php.net/bug.php?id=81720

```
docker run --rm adolfintel/speedtest php -v
PHP 7.4.28 (cli) (built: Feb 17 2022 18:51:32) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
```

> The version of PHP installed on the remote host is prior to 7.4.30. It is, therefore, affected by multiple vulnerabilities as referenced in the Version 7.4.30 advisory.

## Why it should be implemented
Even if the **speedtest** image uses 7.4-apache I recommend you to rebuild this image with a latest version of PHP 7.4
`docker build --no-cache --pull ...`
as a result:
```
docker run --rm php:7.4-apache php -v
PHP 7.4.30 (cli) (built: Jun 10 2022 00:02:02) ( NTS )
````

**Comment by sstidl** [comment]
fixed with #570
