### ISSUE TITLE
Where is the PHP file getIP_serverLocation.php ? 

### ISSUE THREAD

**Issue by typzzh** [librespeed/speedtest#507]
## Description
A short description of what's going on

## Server
Every info you can provide about your server: web server, database, PHP version, ... as well as server-side speedtest settings
If possible, provide an URL to your speedtest so we can check it

## Client
Browser, OS, type of connection, unusual software, ...

## Steps to reproduce
* Do this
* Do that
* Bad stuff happens

## Expected behaviour
What should have happened

## Screenshots
If necessary, add screenshots of the test. 
F12 > Network screenshots can be particularly useful

**Comment by adolfintel** [comment]
The file is automatically generated by getIP.php, it caches the server location obtained from ipinfo (if enabled) to make things faster. It's stored in the same folder.
