### ISSUE TITLE
ipinfo.io gives "Unknown ISP"

### ISSUE THREAD

**Issue by edent** [librespeed/speedtest#511]
## Description
When running the demo service as https://librespeed.org/ , it reports my ISP as unknown.

## Server
https://librespeed.org/

## Client
Firefox, Linux. Chrome, Android.

## Expected behaviour
ipinfo.io should show the correct ISP.

This might be fixed by using https://ifconfig.co/json - although that might also be out of date.

Or by using a free service like https://ipgeolocation.io/pricing.html - although that has 1,000 request limit per day.

Or by using a static database like https://mailfud.org/geoip-legacy/ - although that will need regular updating.

Let me know if you'd like a PR for any of these fixes.

**Comment by YashRajSingh-4799** [comment]
Hi @edent ,
I am looking to contribute in such a useful website i am new to these web service but i will make sure that i will complete it by learning and enhancing my knowledge.
Please assign me this issue so that i can work on it.
and please let me know if you have any resourses for fixing this issue. Currently i dont know how to fix it but i am curious to know about this new domain of web development to enhance my knowledge

**Comment by coderholic** [comment]
The issue doesn't appear to be with our (IPinfo.io)'s data. I also see "Unknown" ISP at https://librespeed.org/

<img width="493" alt="image" src="https://user-images.githubusercontent.com/26079/193460428-336278b6-0035-4290-a3d3-af91c0ec87ed.png">

But on https://ipinfo.io I see this

<img width="518" alt="image" src="https://user-images.githubusercontent.com/26079/193460448-475384b7-497c-4433-baa9-b53fde6383f1.png">

So likely the wrong field is being selected, or the request to IPinfo.io is failing, or something similar.

**Comment by edent** [comment]
Yes, looks like the request to IPinfo.io is failing.

I see a request to `getIP.php?cors=true&isp=true&distance=km&r=0.6038016549816985` which is returning:

```json
{
   "processedString":"12.34.56.78 - Unknown ISP",
   "rawIspInfo":null
}
```

So it looks to me like the error is in https://github.com/librespeed/speedtest/blob/master/backend/getIP.php#L107

**Comment by coderholic** [comment]
The call to IPinfo.io looks OK. Hve you confirmed `getClientIp` is getting the right IP?

**Comment by czadikem** [comment]
Is this still an issue?  If so what are some fixes for it?
