### ISSUE TITLE
Public IP not getting register in database ?

### ISSUE THREAD

**Issue by ochbob** [librespeed/speedtest#544]
## Description
Public IP not getting register in database but OK from webpage result.

## Server
Debian 11 / Apache/2.4.54  / PHP 7.4.33 / Last version Librespeed.

## Client
Safari IOS (not testing anything else)

## Steps to reproduce
Launch a speedtest.

## Expected behaviour
Register public IP in db.

## Screenshots
IP & ISP info from db after speedtest looks like:

> 0.0.0.0
> {"processedString":"0.0.0.0 - Orange S.A., FR (210 km)","rawIspInfo":{"ip":"0.0.0.0","hostname":"REDACTED","city":"Bordeaux","region":"Nouvelle-Aquitaine","country":"FR","loc":"44.8404,-0.5805","org":"AS3215 Orange S.A.","postal":"33000","timezone":"Europe/Paris","readme":"https://ipinfo.io/missingauth"}}

From the speedtest result webpage I got the correct Public IP / and ISP.

Any ideas ?
Thank you :)

**Comment by adolfintel** [comment]
Hi,
It looks like this is enabled https://github.com/librespeed/speedtest/blob/97e0390680c44e132d870961ae824798df3658be/results/telemetry_settings.php#L10

**Comment by ochbob** [comment]
Oh yes, it was the tricks, i did not understand correctly the option.
Thank you :D
