### ISSUE TITLE
Results are inaccurate.

### ISSUE THREAD

**Issue by 1297christian** [librespeed/speedtest#546]
## Description
The test results are to high. A test over a 1 GbE link displays around 1000 Mbps.

## Server
local docker container with standard settings

## Client
Browser, OS, type of connection, unusual software, ...
Chrome, Windows 11, 1 GbE LAN, nothing

## Steps to reproduce
Run a speedtest to a local librespeed host over a 1 GbE link

## Expected behaviour
What should have happened
Considering the protocol overhead the result should be around 940 Mbps.

**Comment by adolfintel** [comment]
This is normal, with the default settings LS tries to compensate for transport overhead. You can disable this if you want, just set overheadCompensationFactor to 1 in the test settings. See here for details: https://github.com/librespeed/speedtest/wiki/Making-a-custom-front-end
