### ISSUE TITLE
Certificate problem on librespeed.org

### ISSUE THREAD

**Issue by Gerard64** [librespeed/speedtest#550]
## Description
On my ISP forums I advised someone to use librespeed.org.
He reported his Netgear router/firewall couldn't access librespeed.org because his router/firewall showed a problem with the website certificate.

## Server
librespeed.org

## Client
Sadly i don't know what browser or OS he uses.

## Steps to reproduce
Visiting the website librespeed.org.

## Expected behaviour
Visting the website without security threat notifications

## Screenshots

![afbeelding](https://user-images.githubusercontent.com/7952595/221936778-bcacbbe8-0028-4be6-8c18-c84951e5da09.png)

**Comment by davidfdzp** [comment]
This is not a problem of librespeed.org, sorry, but of your networking equipment/filters.

**Comment by Gerard64** [comment]
Oke and what is the problem exactly with this Netgear firewall? False positive?

**Comment by davidfdzp** [comment]
Exactly, a false positive by Netgear. Report to them, not here.
