### ISSUE TITLE
New speedtest server - speedtest.sahilister.in - Germany location

### ISSUE THREAD

**Issue by sahilister** [librespeed/speedtest#553]
Domain - https://speedtest.sahilister.in
Sponsored by me (https://sahilister.in)
Hosting on Netcup
Location - Nuremberg, Germany

PS - I had filled the webform a while back but got no response so creating an issue here.

**Comment by adolfintel** [comment]
Thanks for the submission. I did not get the usual notification from the form, that's why it wasn't added, I'll check the email sender.

Btw, you have the post_max_size set too low in your php.ini, it needs to be at least 20M for LS to work properly (it still works but performance is not the best)

**Comment by sahilister** [comment]
@adolfintel sorry for delayed response.

As the setup is behind nginx reverse proxy, have increased the upload size to 20M, though now seeing errors for 21M upload chunks (`...client intended to send too large chunked body`). Do you have a "recommended" upload size or librespeed by design keeps on increasing body size incrementally to test speed?

**Comment by adolfintel** [comment]
20M is the minimum recommended size, but maybe the reverse proxy adds a few bytes of overhead so try 21M.
Either way, the upload test will not send more than 20M per request.

**Comment by sahilister** [comment]
Increased size to 21M in reverse proxy a few hours ago and seeing no new errors regarding body size. Seems to have worked, thanks!

**Comment by sahilister** [comment]
Update - The POST request size has increased to 22M+ now. 

Getting following new errors now - 
```2023/05/05 06:51:45 [error] 658310#658310: *18222243 client intended to send too large chunked body: 22020096+32768 bytes, client: xxx.xxx.xxx.xxx, server: speedtest.sahilister.in, request: "POST /backend/empty.php HTTP/1.1", host: "speedtest.sahilister.in"```

**Comment by yantarou** [comment]
Just for the record and others that may find this (already closed) issue in the future..

Even after setting `client_max_body_size 30M;` in NGINX, this error still shows up:

```
2024/05/06 16:32:26 [error] 1022056#1022056: *418 client intended to send too large chunked body: 31457280+32768 bytes, client: <REDACTED>, server: <REDACTED>, request: "POST /backend/empty.php HTTP/1.1", host: "<REDACTED>"
```

So I wonder if

> Either way, the upload test will not send more than 20M per request.

is still true.
