### ISSUE TITLE
Why does it not work behind a nginx proxy? (Button is not clickable)

### ISSUE THREAD

**Issue by operationairstrike** [librespeed/speedtest#563]

**Comment by adolfintel** [comment]
It's not ideal but it should work, can you send me a link to your server?

**Comment by operationairstrike** [comment]
Not possible currently because it took it offline and deleted the image but I can say what the content was ect

**Comment by adolfintel** [comment]
Sure, post some details

**Comment by operationairstrike** [comment]
Just 502 page basically no modifications and I'm using duckdns and nginx proxy manager

**Comment by sstidl** [comment]
@operationairstrike  please try to give us more details or close the issue.

thanx
s
