### ISSUE TITLE
How to resolve “Unknown ISP” issues

### ISSUE THREAD

**Issue by wcg928** [librespeed/speedtest#575]
IP Address: 202.96.xx.xxx - Unknown ISP

help me

**Comment by gcpmusic** [comment]
Yes please, any help about.
Thanks in advance.

**Comment by sstidl** [comment]
Please let us know what exactly your problem is.
We are using
https://www.getip.org/
If you go there and it's showing 'unknown isp' we can't change anything on our side.

Regards
S

**Comment by adolfintel** [comment]
Actually it seems that the free ipinfo api key no longer works, I'll try to contact them about it.

**Comment by sstidl** [comment]
Fixed it in #583

**Comment by sstidl** [comment]
Provider changed json for paid/registered version of API

**Comment by abdullahdevrel** [comment]
@sstidl I work for IPinfo.

I randomly stumbled across librespeed and pitched the idea to use our free IP databases: https://github.com/librespeed/speedtest/issues/641

But I did not know the project already used our API service. Let me know if there is any way we can help. The API service allows 50k requests a month and up to 100k requests with attribution. One option is that the librespeed.org can make the request from the client side as well. Without a token, we allow up to 1000 requests per day, which should be plenty.

But if you use the free IP database (country, ASN) and host the data, users can make an infinite amount of queries. 

Drop a comment on https://github.com/librespeed/speedtest/issues/641 when you are available. Thank you.
