### ISSUE TITLE
aarch64 Docker Image

### ISSUE THREAD

**Issue by jzbor** [librespeed/speedtest#588]
## Description
It would be nice if there was an official aarch64 image provided alongside [the official x86_64 images](https://github.com/librespeed/speedtest/pkgs/container/speedtest).

## Why it should be implemented
A lot of educational homelab devices (e.g. Raspberry Pi) run on this architecture, but there are also cloud hosts like Hetzner that provide cheap aarch64 boxes.

**Comment by jzbor** [comment]
[Seems like it should be as easy as adding a "platform" option to the workflow.](https://github.com/docker/setup-buildx-action#customizing)

**Comment by sstidl** [comment]
should be fixed by #590

**Comment by jzbor** [comment]
Thanks a lot!
