### ISSUE TITLE
long time only runing download or upload test

### ISSUE THREAD

**Issue by sky52292** [librespeed/speedtest#595]
## Description
i want long time only runing download (1 hours or more)  or  upload test. 

## Why it should be implemented
Test whether the WiFi device is stable, 
Continuous testing of traffic
http speedtest is easly.

## Optional: implementation suggestions
If you have experience in this field, feel free to give us suggestions

## Optional: screenshots
Add some screenshots, mockups, ... if they help clarify what you want

**Comment by adolfintel** [comment]
You can configure the test to be 1h long if you want, just take one of the examples and set `time_auto` to false and `time_dl_max` and `time_ul_max` to 3600.

See here for more info: https://github.com/librespeed/speedtest/wiki/Making-a-custom-front-end
