### ISSUE TITLE
Another test server in Asia

### ISSUE THREAD

**Issue by galpt** [librespeed/speedtest#596]
## Description
If it's possible, please add this one:
https://net.0ms.dev/

## Why it should be implemented
Another server in Asia for users to choose would be great.
I see there's none in SG, so this would help.

We did sent a [submit](https://librespeed.org/submit/) request some hours ago, but not so sure on how to fill the form correctly.
But `URL to the server` is basically the same as above.

## Optional: implementation suggestions
It's using [speedtest-go](https://github.com/librespeed/speedtest-go), hopefully that won't be a problem.

**Comment by adolfintel** [comment]
Sorry, I'm very busy these days. I checked your server submission and it is now publicly listed.

Thanks for your submission :)
