### ISSUE TITLE
Requesting to remove "0ms.dev" from librespeed.org

### ISSUE THREAD

**Issue by galpt** [librespeed/speedtest#601]
Sorry for the sudden request. This is related to https://github.com/librespeed/speedtest/issues/596.
I'm requesting for the removal of that server.

We've been changing and optimizing stuff in our server lately, and for the time being decided to disable our librespeed & ookla servers until everything's really stable again.
We hope to support this project again in the future when the infrastructure is ready for that. :)

**Comment by adolfintel** [comment]
Done!
