### ISSUE TITLE
No link Result in screen

### ISSUE THREAD

**Issue by bartounet16** [librespeed/speedtest#611]
## Description
In old version i had link about result that display in screen
now I have no link result in display

## Server
I use Docker Image
version: '3.7'
services:
  speedtest:
    container_name: speedtest
    image: ghcr.io/librespeed/speedtest:latest
    restart: always
    environment:
      MODE: standalone
      TITLE: "Test de débit vers l'hôtel d'agglomération"
      TELEMETRY: "True"
      #ENABLE_ID_OBFUSCATION: "false"
      REDACT_IP_ADDRESSES: "true"
      PASSWORD: "*"
      #EMAIL:
      #DISABLE_IPINFO: "false"
      DISTANCE: "km"
      #WEBPORT: 80
    volumes:
      - /DOCKER/LIBRESPEED/config:/config
    ports:
      - "8089:80" # webport mapping (host:container)

## Client
Edge, Windonws 10

## Expected behaviour
i would to have this link !!!
![image](https://github.com/librespeed/speedtest/assets/1244020/5ab6e50f-85c7-4190-9af5-e1ba5798e569)

but i have nothing

## Screenshots
If necessary, add screenshots of the test.
F12 > Network screenshots can be particularly useful

**Comment by sstidl** [comment]
Please use "true" not "True" in your docker-compose.yml
