### ISSUE TITLE
Synology docker container: download speed is always 0

### ISSUE THREAD

**Issue by zypA13510** [librespeed/speedtest#613]
## Description
I run librespeed via docker-compose. When I run the speedtest, the download speed is always 0 but upload is normal.

In the network panel, garbage.php would all fail with (canceled) on Chrome or (aborted) on Firefox.
But opening the garbage.php request in a new tab works (it begins downloading a file called random.dat).

The same setup works fine if reverted to previous image version `adolfintel/speedtest:latest` (sha256:1f828fe8337470d2ed5841176bfa6633fd94bda97261a636c35d0bef60a35270). It also works on GCP using the new image.
| image | Google Compute Engine / Debian 12 | Synology / DiskStation Manager 7 (Linux 4.4 x86_64) |
| --- | --- | --- |
| adolfintel/speedtest | (not tested) | ✅ |
| ghcr.io/librespeed/speedtest | ✅ | ❌ |

Additionally, I've compared the docker log from both image when running on the same Synology server, I noticed that on the old image, as soon as the test goes to the download step, there will be multiple log entries containing "garbage.php" printed. Whereas on the new image, the "garbage.php" logs only appear **after** the download test ended with 0 Mbit/s result and before the upload test.

Looks like a compatibility/regression issue?

## Server
docker-compose.yml
```yaml
version: "3.7"
services:
  librespeed:
    image: ghcr.io/librespeed/speedtest
    environment:
      MODE: standalone
    restart: unless-stopped
    ports:
      - 5202:80
```
Docker version 20.10.23, build 876964a
Docker Compose version v2.9.0-6413-g38f6acd
Using Synology Container Manager as a frontend for docker, but I don't think it's any different than running docker in CLI.

## Client
Tested on Chrome v126, Firefox v126, Edge v123, Edge v124, neither of which worked.
Windows 11 23H2 build 22631.3447

## Steps to reproduce
1. On the server side, create docker-compose.yml as above.
2. Start the docker-compose project.
3. On the client side, go to `http://<IP>:5202` in the browser
4. Click start button to begin speedtest.

## Expected behaviour
Download speed is non-zero.

## Screenshots
![image](https://github.com/librespeed/speedtest/assets/8077540/a398d412-4652-4406-977c-7c46eb7737d3)

**Comment by msalmasi** [comment]
Can confirm I have the same issue running in docker. Also on Synology if that somehow makes a difference, but I am using CLI to manage containers.

**Comment by zypA13510** [comment]
I cannot reproduce it on GCP with Debian 12. Seems like it may be a Synology-specific issue, or it could be related to software version/configuration.

**Comment by zypA13510** [comment]
On Chrome/Firefox, the issue is the same. But the network panel gives "(canceled)" as the reason.
I tried to open the xhr request URL (garbage.php) in a new tab, it works normally - it starts downloading a file called random.dat.
@adolfintel any idea why? What can I do to troubleshoot this issue?

**Comment by kimsonvu** [comment]
Same story here after i move from DS218+ to DS1621+. I don't know why.

**Comment by zypA13510** [comment]
Some additional information: the docker image `adolfintel/speedtest:latest` (I suppose it is a previous version) works fine. This issue only affects the image `ghcr.io/librespeed/speedtest:latest`.

**Comment by kimsonvu** [comment]
> Some additional information: the docker image [`adolfintel/speedtest:latest`](https://registry.hub.docker.com/r/adolfintel/speedtest) (I suppose it is a previous version) works fine. This issue only affects the GitHub image `ghcr.io/librespeed/speedtest:latest`.

Thanks to share this detail. I confirm that it work well with me!
