### ISSUE TITLE
Sponsoring a server? for librespeed.org

### ISSUE THREAD

**Issue by kingofkya** [librespeed/speedtest#616]
Is there any info on getting added if you wanted to sponsor a server, I work for a company that may be interested, As we already have the servers setup publicly already with a 10-40gbit connection we also host okkla speed test server so its not a new thing for us. As the US servers selection seams to be rather limited at the moment, and seams to not max out the connection.

I could provide a server for Denver, Los Angeles, Las Vegas, Chicago, and Amsterdam if interested.

**Comment by adolfintel** [comment]
Hi :)

You can send me the details for your servers at info@fdossena.com and I'll add them to our public list.

Thanks
