### ISSUE TITLE
Can we get rid of the php dependency and reduce it to a project that only relies on nginx deployment?

### ISSUE THREAD

**Issue by O-sheng** [librespeed/speedtest#653]
Can we get rid of the php dependency and reduce it to a project that only relies on nginx deployment?
I tried to modify the code, can only achieve download, speed measurement, and a little faster
![image](https://github.com/user-attachments/assets/9e13e4aa-a914-4456-9924-3acdbffc2801)

**Comment by adolfintel** [comment]
Yes, you can just use a large file instead of garbage.php, it's mentioned in doc.md
