### ISSUE TITLE
Add my instance

### ISSUE THREAD

**Issue by vdbhb59** [librespeed/speedtest#658]
Hi Mate,

I would like to offer my instance to be added for public usage.
Limit 48500 requests per month
City: Nürnberg
Region: Bavaria
Country: Germany
Provider: netcup GmbH
Instance: https://speed.flossboxin.org.in/

I have not changed logo or anything, and would like to keep it as official public instance for your great service.

Please also let me know, where in the code is this instance setup? I tried to find it, but could not, and hence could not raise a MR.

Edit/Update: I would like to have server selection from the drop down like yours. Is it possible for me to get those selections as well? If yes, how can I do that mate?

**Comment by adolfintel** [comment]
Hi,

The server list is not in this repo, that's why you can't find it.

I can add it to the list but I can't seem to get more than 2-300mbps from your server, which is pretty low considering that I'm near milan.

What kind of server is it and how much bandwidth do you have? If we make it public it will get easily overloaded with multiple tests if you don't have at least 1gbps

**Comment by vdbhb59** [comment]
Here are the details:
https://www.netcup.eu/bestellen/produkt.php?produkt=3691
Network: 2500 MBit/s
AMD EPYC™ 9634
8 GB DDR5 ECC RAM
KVM technology
NVMe SSD + RAID

Bandwidth maybe throttled if it goes beyond 300Mbits, I think so (reading from their server details).

**Comment by adolfintel** [comment]
There could be a cap at 300mbps per IP, that would be a problem :thinking: 

I don't see it mentioned on that page, where did you see it?

**Comment by vdbhb59** [comment]
https://www.netcup.eu/vserver/#root-server-details

But I can see, it is capped only upon 3TB traffic. So, not sure why I am not getting the real speed. Maybe I need to something on my server settings for network?

![image](https://github.com/user-attachments/assets/92b9482e-0d03-4016-ab9e-438641e9ed09)

**Comment by vdbhb59** [comment]
Also, I am unable to get the stats working. I have setup pgsql, and given all the necessary details in the telemetry_settings.php. I have changed owner to the user where it is installed, but not getting any results back.

**Comment by adolfintel** [comment]
Do you have the pgsql pdo moduled enabled in php.ini?

Also, check your web server log file, it's usually in /var/log/apache2 (assuming you're using apache), it will probably tell you what's wrong
