### ISSUE TITLE
When I use an image with the tag latest-alpine, the container unexpectedly occupies port 443 for https

### ISSUE THREAD

**Issue by blueberry-pie-11** [librespeed/speedtest#659]
## Description
If you use the WEBPORT variable to set a specific port (such as 5000), the container will normally provide an http interface on port 5000, but will additionally occupy port 443 for https services.
When docker uses the host network mode, if nginx is used as a reverse proxy (https), it will cause a conflict with nginx's port 443, and eventually it will be stuck in a continuous restart.

**Comment by sstidl** [comment]
removed apache2-ssl dependency. will be release with #678

**Comment by sstidl** [comment]
fixed in latest docker images
