### ISSUE TITLE
Consider to add support for IP2Location.io API

### ISSUE THREAD

**Issue by ip2location** [librespeed/speedtest#669]
## Description
Would you like to add support of our service into your project for geolocation function? Our service provided 500 queries per day for keyless query, or 30000 queries per month if you sign up our free plan. You can read more on the result returned via [our documentation](https://www.ip2location.io/ip2location-documentation).

## Why it should be implemented
Can act as another choice to your users.

## Optional: implementation suggestions
No

## Optional: screenshots
No

**Comment by sstidl** [comment]
We already integrated ipinfo. No need for another one.
