### ISSUE TITLE
librespeed.org down?

### ISSUE THREAD

**Issue by adsche** [librespeed/speedtest#674]
## Description
The site librespeed.org (linked from the README of this repo) seems to be down.

https://downforeveryoneorjustme.com/librespeed.org

<img width="714" alt="Screenshot 2024-10-22 at 21 33 13" src="https://github.com/user-attachments/assets/39ec2291-fcbd-448a-b39a-7fbf3a311267">

## Server
librespeed.org

## Client
Firefox on macos

**Comment by f3n3k** [comment]
yep, same here.

**Comment by adolfintel** [comment]
Caddy crashed, now it's up again
