### ISSUE TITLE
postgres is not supported in docker image

### ISSUE THREAD

**Issue by jacekjaros** [librespeed/speedtest#675]
## Description
When deploy latest docker image and enable telemetry no results are written to database because of missing libpq5 package.

## Server
- docker image - ghcr.io -> librespeed/speedtest:latest

## Env
DB_HOSTNAME 	postgres.int.xxx
DB_NAME 	librespeed
DB_PASSWORD 	XXXXXXX
DB_PORT 	5432
DB_TYPE 	postgresql
DB_USERNAME 	librespeed
EMAIL 	jacek@XXXXX
ENABLE_ID_OBFUSCATION 	false
IPINFO_APIKEY 	XXX
MODE 	standalone
TELEMETRY 	true

## Client
Firefox - latest

## Steps to reproduce
- use latest docker image
- set provided env variables
- do speed test
- check docker logs and data in postgres

## Expected behavior
speed test data stored in postgres

## Docker logs
`<b>Warning</b>:  PHP Startup: Unable to load dynamic library 'pgsql.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20230831/pgsql.so (libpq.so.5: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20230831/pgsql.so.so (/usr/local/lib/php/extensions/no-debug-non-zts-20230831/pgsql.so.so: cannot open shared object file: No such file or directory)) in <b>Unknown</b> on line <b>0</b><br />`

**Comment by sstidl** [comment]
should be fixed with 0c31f1de6d03e8d39150ef354be8750d3f72a341

**Comment by sstidl** [comment]
will be released with #678

**Comment by sstidl** [comment]
is now working in latest docker images
